### PR TITLE
Patch for the failure of functions with void return type and with return statement

### LINKED ISSUE #432: Creating pushforward fails for function with `void` return type that contains statement `return;`
Minimum reproducible example: 
```cpp
void some_fn() {
  return;
}

double fn(double i) {
  some_fn();
  return i;
} 

int main() {
  auto d_fn = clad::differentiate(fn);
}
```

**Root cause of the error**
In pushforward differentiation mode, `ForwardModeVisitor::VisitReturnStmt` tries to transform `return res` to `return {res, _d_res}`, but this transformation fails if `return` statement does not has any associated return value.

### PR DESCRIPTION
**Pull request by Nirhar**
Prior to this patch, clad would throw an assertion error when attempting to differentiate void functions that contain a return statement.
The assertion error would indicate that there was an attempt to differentiate a nullptr.
This Patch checks if the there is an expression associated with the null pointer and only if there is one, we differentiate it.
Added tests for the same

This patch fixes #432

### CODE REVIEW

File: lib/Differentiator/ForwardModeVisitor.cpp [hunk 1]
```diff
@@ -747,6 +747,10 @@ namespace clad {
   }
 
   StmtDiff ForwardModeVisitor::VisitReturnStmt(const ReturnStmt* RS) {
+    //If there is no return value, we must not attempt to differentiate
+    if(RS->getRetValue()==nullptr){
+      return nullptr;
```
Comment (parth-07) [inline lib/Differentiator/ForwardModeVisitor.cpp:752]: We do not use braces with one-liner `if` statements.

Comment (Nirhar) [reply lib/Differentiator/ForwardModeVisitor.cpp:752]: have corrected it

**Review by parth-07 — COMMENTED** [review]
Looks good.

I'd suggest improving the commit message style. Maybe [this](https://chris.beams.io/posts/git-commit/) would be a useful read.

File: lib/Differentiator/ForwardModeVisitor.cpp [hunk 2]
```diff
@@ -747,6 +747,10 @@ namespace clad {
   }
 
   StmtDiff ForwardModeVisitor::VisitReturnStmt(const ReturnStmt* RS) {
+    //If there is no return value, we must not attempt to differentiate
+    if(RS->getRetValue()==nullptr)
```
Comment (vgvassilev) [inline lib/Differentiator/ForwardModeVisitor.cpp:751]: @Nirhar, can you run clang-format?

@parth-07, can you add a section in the docs about running clang-format?

Comment (parth-07) [reply lib/Differentiator/ForwardModeVisitor.cpp:751]: Yes, I will add a section for this in the docs.

Comment (vgvassilev) [reply lib/Differentiator/ForwardModeVisitor.cpp:751]:
```suggestion
    if (!RS->getRetValue())
```

**Review by vgvassilev — APPROVED** [review]
Thanks for the fix! LGTM!
