### PR TITLE
Fix pointer arithmetic in fwd mode

### LINKED ISSUE #978: Pointer arithmetics don't work in forward mode
This is similar to #972, only now it's about pointer arithmetic that backward mode supports but not the forward mode.

It would be nice if backward mode and forward mode have the same level of C++ language support to avoid more surprises like this :slightly_smiling_face:

Reproducer:
```c++
// Compile with clang++ -std=c++11 -fplugin=install/lib/clad.so -I./install/include cladIssue.cxx -o cladIssue

#include "clad/Differentiator/Differentiator.h"

#include <iostream>
#include <vector>

double wrapper(double* params, double const* constants) {
   double c0 = *(constants + 0);
   return params[0] * c0;
}

int main()
{
   auto diff = clad::differentiate(wrapper, "params[0]"); // doesn't work
   auto grad = clad::gradient(wrapper, "params"); // works!

   double x = 2.0;
   double y = 2.0;
   double result = 0.0;
   grad.execute(&x, &y, &result);

   std::cout << result << std::endl;
   std::cout << diff.execute(&x, &y) << std::endl;
}
```
Compiler output:
```txt
cladIssue.cxx:9:30: warning: attempt to differentiate unsupported operator,  derivative                          set to 0
   double c0 = *(constants + 0);
                             ^
error: indirection requires pointer operand ('int' invalid)
1 warning and 1 error generated.
```

### PR DESCRIPTION
**Pull request by vaithak**
fixes #978

### CODE REVIEW

File: lib/Differentiator/BaseForwardModeVisitor.cpp [hunk 1]
```diff
@@ -1501,9 +1501,17 @@ BaseForwardModeVisitor::DifferentiateVarDecl(const VarDecl* VD,
...
+  if (VD->getType()->isPointerType() && !initDx) {
+    // initialize with nullptr.
+    // NOLINTBEGIN(cppcoreguidelines-owned-memory)
+    initDx =
+        new (m_Context) CXXNullPtrLiteralExpr(VD->getType(), VD->getBeginLoc());
+    // NOLINTEND(cppcoreguidelines-owned-memory)
+  }
+  VarDecl* VDDerived =
+      BuildVarDecl(VD->getType(), "_d_" + VD->getNameAsString(), initDx,
+                   VD->isDirectInit(), nullptr, VD->getInitStyle());
```
Comment (vgvassilev) [inline lib/Differentiator/BaseForwardModeVisitor.cpp:1514]:
```suggestion
                   VD->isDirectInit(), /*TSI=*/nullptr, VD->getInitStyle());
```

**Comment by vaithak** [comment]
I am working on one more fix related to handling function calls with pointers, will send a separate PR for that as it takes a bit more debugging. The issue is essentially related to #762, but in forward mode.
