### PR TITLE
Fix issue #793: Implement slab based tape

### LINKED ISSUE #793: Do not relocate the tape elements
In the current implementation of `clad::tape` we ensure the elements are contiguous. The `grow` operation relocates the elements when the size exceeds the tape capacity:

https://github.com/vgvassilev/clad/blob/f242077c9b386a9711cdb257b1126a07b52c5006/include/clad/Differentiator/Tape.h#L119

Instead we should allocate slabs of 32 or 64 elements and the last element should point to the next slab.

### PR DESCRIPTION
**Pull request by aditimjoshi**
Fixes #793. Modifies tape implementation to a slab based structure instead of relocating elements each time the tape grows in size.

### CODE REVIEW

File: include/clad/Differentiator/Tape.h [hunk 1]
```diff
@@ -9,159 +9,135 @@
...
+          while (last->next) last = last->next;
+          last->next = new_slab;
+        }
+      }
+
+      Slab* slab = _head;
+      size_t i = _size / slab_size;
+      while (i--) slab = slab->next;
+
+      ::new (const_cast<void*>(static_cast<const volatile void*>(slab->elements() + (_size % slab_size)))) T(std::forward<ArgsT>(args)...);
```
[the remark this answers is not in the document]
Comment (vgvassilev) [reply include/clad/Differentiator/Tape.h]: There must be some idiom that's used in STL for such operations instead of these casts...

File: include/clad/Differentiator/Tape.h [hunk 2]
```diff
@@ -9,160 +9,185 @@
 #include "clad/Differentiator/CladConfig.h"
 
 namespace clad {
-  /// Dynamically-sized array (std::vector-like), primarily used for storing
-  /// values in reverse-mode AD inside loops.
   template <typename T>
   class tape_impl {
-    T* _data = nullptr;
+    struct Slab {
+      alignas(T) char raw_data[1024 * sizeof(T)];
```
Comment (vgvassilev) [inline include/clad/Differentiator/Tape.h]: Please move the `1024` into a constant explaining why it was picked -- probably move the constexpr variable a bit up.

File: include/clad/Differentiator/Tape.h [hunk 3]
```diff
@@ -9,160 +9,185 @@
 #include "clad/Differentiator/CladConfig.h"
 
 namespace clad {
-  /// Dynamically-sized array (std::vector-like), primarily used for storing
-  /// values in reverse-mode AD inside loops.
```
Comment (vgvassilev) [inline include/clad/Differentiator/Tape.h:13]: We should also add some documentation for the new implementation.

File: include/clad/Differentiator/Tape.h (hunk 2 above)
Comment (vgvassilev) [inline include/clad/Differentiator/Tape.h]: Can you also test with bigger objects where `sizeof(T)` influences the overall size?

File: include/clad/Differentiator/Tape.h [hunk 4]
```diff
@@ -9,160 +9,185 @@
...
   template <typename T>
```
Comment (vgvassilev) [inline include/clad/Differentiator/Tape.h]: Here we should take `SBO_SIZE` and `SLAB_SIZE` as parameters with default values.

File: include/clad/Differentiator/Tape.h [hunk 5]
```diff
@@ -9,160 +9,185 @@
...
   class tape_impl {
-    T* _data = nullptr;
+    struct Slab {
+      alignas(T) char raw_data[1024 * sizeof(T)];
+      Slab* next;
+      Slab() : next(nullptr) {}
```
Comment (kchristin22) [inline include/clad/Differentiator/Tape.h]: Hi, great work! I tested it on CUDA, and to compile it should be:
```
CUDA_HOST_DEVICE Slab() : next(nullptr) {}
```

File: include/clad/Differentiator/Tape.h [hunk 6]
```diff
@@ -9,160 +9,185 @@
...
+      T* elements() { return reinterpret_cast<T*>(raw_data); }
```
Comment (kchristin22) [inline include/clad/Differentiator/Tape.h]: same here:
```
CUDA_HOST_DEVICE T *elements() { return reinterpret_cast<T*>(raw_data); } 
```

File: include/clad/Differentiator/Tape.h [hunk 7]
```diff
@@ -9,139 +9,155 @@
...
-      _size += 1;
+      if (_size < SBO_SIZE) {
+        // Store in SBO buffer
+        ::new (const_cast<void*>(static_cast<const volatile void*>(sbo_elements() + _size)))
+            T(std::forward<ArgsT>(args)...);
+      } else {
+        // Transition to dynamic storage if needed
+        if (m_using_sbo) {
+          m_using_sbo = false;
+        }
```
Comment (vgvassilev) [inline include/clad/Differentiator/Tape.h]:
```suggestion
        if (m_using_sbo)
          m_using_sbo = false;
```

File: include/clad/Differentiator/Tape.h [hunk 8]
```diff
@@ -9,139 +9,155 @@
 #include "clad/Differentiator/CladConfig.h"
 
 namespace clad {
-  /// Dynamically-sized array (std::vector-like), primarily used for storing
-  /// values in reverse-mode AD inside loops.
-  template <typename T>
+  /// A dynamic slab-based vector-like container with Small Buffer Optimization (SBO),
+  /// primarily used for storing values in reverse-mode AD.
+  /// Stores elements in a static buffer first, then falls back to dynamically
+  /// allocated linked slabs if capacity exceeds SBO.
```
Comment (vgvassilev) [inline include/clad/Differentiator/Tape.h:15]:
```suggestion
  /// allocated linked slabs if capacity exceeds small buffer optimization (SBO).
```

File: include/clad/Differentiator/Tape.h [hunk 9]
```diff
@@ -1,168 +1,252 @@
...
-      // allocation properly.
-      for (; first != last; ++first, (void)++current) {
-        ::new (const_cast<void*>(
-            static_cast<const volatile void*>(clad_addressof(*current))))
-          T(std::move(*first));
-      }
+      // Construct element in-place
+      ::new (const_cast<void*>(static_cast<const volatile void*>(
+          slab->elements() + ((_size - SBO_SIZE) % SLAB_SIZE))))
+          T(std::forward<ArgsT>(args)...);
```
Comment (vgvassilev) [inline include/clad/Differentiator/Tape.h]:
```suggestion
      T* location = slab->elements() + ((_size - SBO_SIZE) % SLAB_SIZE);
      ::new (static_cast<void*>(location)) T(std::forward<ArgsT>(args)...);
```
Can we do something like this?

File: include/clad/Differentiator/Tape.h [hunk 10]
```diff
@@ -1,168 +1,252 @@
...
+
+  /// Remove the last value from the tape.
+  CUDA_HOST_DEVICE void pop_back() {
+    assert(_size);
+    _size--;
+    at(_size)->~T();
+  }
+
+private:
+  // Returns pointer to element at specified index, handling SBO or slab lookup
```
Comment (vgvassilev) [inline include/clad/Differentiator/Tape.h]:
```suggestion
  /// Returns pointer to element at specified index, handling SBO or slab lookup
```

File: include/clad/Differentiator/Tape.h [hunk 11]
```diff
@@ -1,168 +1,252 @@
...
+/// slabs if capacity exceeds SBO.
+template <typename T, std::size_t SBO_SIZE = 64, std::size_t SLAB_SIZE = 1024>
+class tape_impl {
+  /// A block of contiguous storage allocated dynamically when SBO capacity is
+  /// exceeded.
+  struct Slab {
+    alignas(T) char raw_data[SLAB_SIZE * sizeof(T)]{};
+    Slab* next;
+    CUDA_HOST_DEVICE Slab() : next(nullptr) {}
+    CUDA_HOST_DEVICE T* elements() { return reinterpret_cast<T*>(raw_data); }
```
Comment (vgvassilev) [inline include/clad/Differentiator/Tape.h]: From c++17 onward we can/should use:
`return std::launder(reinterpret_cast<T*>(addr));`

Can we have an ifdef?

File: include/clad/Differentiator/Tape.h [hunk 12]
```diff
@@ -1,168 +1,252 @@
...
+  };
 
-    CUDA_HOST_DEVICE const_reference operator[](std::size_t i) const {
-      assert(i < _size);
-      return begin()[i];
-    }
+  alignas(T) char m_static_buffer[SBO_SIZE * sizeof(T)];
```
Comment (vgvassilev) [inline include/clad/Differentiator/Tape.h]:
```suggestion
  std::aligned_storage_t<sizeof(T), alignof(T)> data[N];
```
Maybe something like that?

**Review by vgvassilev — COMMENTED** [review]
We are getting very close to merging this.

File: include/clad/Differentiator/Tape.h (hunk 11 above)
Comment (aditimjoshi) [reply include/clad/Differentiator/Tape.h]: I'll do this for both the sbo_elements() functions as well right?

File: include/clad/Differentiator/Tape.h (hunk 9 above)
Comment (aditimjoshi) [reply include/clad/Differentiator/Tape.h]: I tried this but it won't work unless we add (const_cast<void*>(static_cast<const volatile void*>(location))). For just (static_cast<void*>(location)) it gives the error 
error: static_cast from 'const int *' to 'void *' is not allowed

File: include/clad/Differentiator/Tape.h (hunk 11 above)
Comment (vgvassilev) [reply include/clad/Differentiator/Tape.h]: Yes, please.

File: include/clad/Differentiator/Tape.h (hunk 12 above)
Comment (aditimjoshi) [reply include/clad/Differentiator/Tape.h]: std::aligned_storage_t was introduced in c++-14. I think version 11 had std::aligned_storage but it's going to be deprecated in later versions.

File: include/clad/Differentiator/Tape.h [hunk 13]
```diff
@@ -1,168 +1,252 @@
...
+    return m_index != other.m_index;
+  }
+};
+
+/// A dynamic slab-based vector-like container with Small Buffer Optimization
+/// (SBO), primarily used for storing values in reverse-mode AD. Stores elements
+/// in a static buffer first, then falls back to dynamically allocated linked
+/// slabs if capacity exceeds SBO.
+template <typename T, std::size_t SBO_SIZE = 64, std::size_t SLAB_SIZE = 1024>
+class tape_impl {
```
[the remark this answers is not in the document]
Comment (vgvassilev) [reply include/clad/Differentiator/Tape.h:70]: @aditimjoshi, do we want to try to address this?

[the remark this answers is not in the document]
Comment (aditimjoshi) [reply include/clad/Differentiator/Tape.h:70]: The old tape implementation had also defined a destructor without defining the rest so I was thought it would be fine but if there's a case I missed where it will cause errors or if it seems better to address it then I can add it.

[the remark this answers is not in the document]
Comment (vgvassilev) [reply include/clad/Differentiator/Tape.h:70]: Let's write them.

File: include/clad/Differentiator/Tape.h [hunk 14]
```diff
@@ -1,168 +1,330 @@
...
+  using const_reference = const T&;
+  using pointer = T*;
+  using const_pointer = const T*;
+  using size_type = std::size_t;
+  using difference_type = std::ptrdiff_t;
+  using value_type = T;
+  using iterator = tape_iterator<T, SBO_SIZE, SLAB_SIZE>;
+  using const_iterator = tape_iterator<const T, SBO_SIZE, SLAB_SIZE>;
+
+  CUDA_HOST_DEVICE tape_impl() = default;
```
Comment (vgvassilev) [inline include/clad/Differentiator/Tape.h:125]: That's enough -- we should not encourage people to copy the tape. Perhaps once we have a valid use case (so far we don't) we can implement the move operations. Let's keep only this line and delete the other operators with a comment explaining that we don't want the tape to be copied (AD does not generally need that).
