### PR TITLE
Fix crashing for differentiating static member functions

### LINKED ISSUE #1270: Clad crashes when trying to differentiate a static member function
Clad crashes when trying to differentiate a static member function.

Reproducible example:

```cpp
class A {
public:
static double add(double u, double v) {
  return u + v;
}
};

double fn(double u, double v) {
  return A::add(u, v);
}

int main() {
  auto d_fn = clad::gradient(fn);
}
```

### PR DESCRIPTION
**Pull request by Rohan-T144**
Trying to differentiate static member function failed with an out of bounds error, which this PR fixes.

Fixes #1270

### CODE REVIEW

File: lib/Differentiator/ReverseModeVisitor.cpp [hunk 1]
```diff
@@ -1798,9 +1798,11 @@ Expr* ReverseModeVisitor::getStdInitListSizeExpr(const Expr* E) {
       pullbackRequest.EnableVariedAnalysis = m_DiffReq.EnableVariedAnalysis;
       for (size_t i = 0, e = FD->getNumParams(); i < e; ++i) {
         const auto* PVD = FD->getParamDecl(i);
+        // static member function doesn't have `this` pointer
+        size_t offset = (bool)MD && !MD->isStatic();
```
Comment (vgvassilev) [inline lib/Differentiator/ReverseModeVisitor.cpp:1802]:
```suggestion
        size_t offset = (bool)MD && MD->isInstance(); 
```

File: lib/Differentiator/ReverseModeVisitor.cpp [hunk 2]
```diff
@@ -1819,7 +1821,7 @@ Expr* ReverseModeVisitor::getStdInitListSizeExpr(const Expr* E) {
         pullbackFD = m_Builder.HandleNestedDiffRequest(pullbackRequest);
 
       if (pullbackFD) {
-        if (MD) {
+        if (MD && !MD->isStatic()) {
```
Comment (vgvassilev) [inline lib/Differentiator/ReverseModeVisitor.cpp:1824]:
```suggestion
        if (MD && MD->isInstance()) {
```

File: lib/Differentiator/VisitorBase.cpp [hunk 3]
```diff
@@ -717,7 +717,8 @@ namespace clad {
                                        llvm::MutableArrayRef<Expr*> argExprs,
                                        bool useRefQualifiedThisObj /*=false*/) {
     Expr* call = nullptr;
-    if (auto derMethod = dyn_cast<CXXMethodDecl>(FD)) {
+    auto* derMethod = dyn_cast<CXXMethodDecl>(FD);
+    if (derMethod && derMethod->isInstance()) {
```
Comment (vgvassilev) [inline lib/Differentiator/VisitorBase.cpp:721]:
```suggestion
    auto* derMethod = ;
    if (const auto* MD = dyn_cast<CXXMethodDecl>(FD)) {
      if (MD->isInstance())
```

**Review by vgvassilev — COMMENTED** [review]
Please squash all commits into one and run `git-clang-format HEAD~`.

**Comment by vgvassilev** [comment]
Please write a more descriptive commit message and include in the end `Fixes #1270`.
