### PR TITLE
Fix/clad params types

### LINKED ISSUE #385: Improve derivative type consistency.
```cpp
double fn(float f, float* arr) {
  float another_f;
  float another_arr[5];
}
```

This function will have the derived function signature as follows:

```cpp
double fn_grad(float f, float* arr, clad::array_ref<double> d_f, clad::array_ref<double>(arr)) {
  float d_another_f = 0;
  float another_f;
  clad::array<float> d_another_arr(5UL);
  float another_arr[5];
}
```

Please notice that `f` argument has the effective derivative type of `double` whereas `another_f` local variable has the effective derivative type of `float`.
And `arr` argument has the effective derivative type of `double*` whereas `another_arr` local variable has the effective derivative type of `float*`. 
Even though `f` and `another_f` are of the same type and `arr` and `another_arr` are of the same type. 

These type inconsistencies can make it difficult to reason behaviour of the program and also makes it more confusing for the users to estimate the derivative type of some variable. We should strive to keep such inconsistencies to as minimum as possible. 
One way to remove these inconsistencies is as follows:
Derivative obtained by differentiation of a variable of type `A` with respect to a variable of type `B` should always be of type `B` when `A` and `B` are both scalar numerical types.

### PR DESCRIPTION
**Pull request by ioanaif**
This aims to fix #385 :

- [x]   Preserving param types [1]:
```
int someFn(int i, double j) { return 7*i + 9*j; }
int fn(int i, double j) { return someFn(i, j) + 309; }
auto f_dx =  clad::gradient(fn);
void fn_grad(int i, double j, clad::array_ref<int> d_i, clad::array_ref<double> d_j)
```

         
- [x]  Preserving param types [2]:
```
void someFn(float i, int j, double &out) {
   out = 7*i + 9*j;
}
double fn(float i, int j, double &out) {
   someFn(i, j, out);
   return out + 309;
}
```

- [x]  Preserving param types - array type:
```
double addArr(int *arr, double n) {
   double ret = 0;
   for (int i = 0; i < n; i++) 
      ret += arr[i];
      return ret;
   }
double f(int* arr) { return addArr(arr, 4)};
auto f_dx = clad::gradient(f);
```

### CODE REVIEW

**Comment by parth-07** [comment]
Regarding the failing MacOS tests for `real_pullback` and other `std::complex` functions, since the platforms are using different implementations of the standard library, we are currently using a complicated regex expression in LIT `CHECK`s to match both of them, this isn't a good solution. We have two ways to proceed: 

1) Have separate `CHECK`s directives for MacOS and Linux Github runners when the source function is different for the platforms. This can be done as follows: 

```cpp
#ifdef __APPLE__
// CHECK directives for macos
#else
// CHECK directives for linux
#endif
```

Alternatively, we can also check if `libc++` is being used as a standard library or `libstdc++` using the preprocessor flag `_LIBCPP_VERSION`. 

2) We can avoid checking LIT `CHECK`s for standard library functions if the above-mentioned approach becomes difficult to maintain.

**Comment by ioanaif** [comment]
> 1. Have separate `CHECK`s directives for MacOS and Linux Github runners when the source function is different for the platforms. This can be done as follows:
> 
> ```c++
> #ifdef __APPLE__
> // CHECK directives for macos
> #else
> // CHECK directives for linux
> #endif
> ```

It seems that it skips these conditions, so I made the regex more lenient in that special case, but this might raise other issues in the future.

File: lib/Differentiator/ReverseModeVisitor.cpp [hunk 1]
```diff
@@ -2883,12 +2820,18 @@ namespace clad {
     // derivative variables should always be of non-const type.
     xValueType.removeLocalConst();
     QualType nonRefXValueType = xValueType.getNonReferenceType();
-    if (nonRefXValueType->isRealType())
-      return GetCladArrayRefOfType(yType);
-    else
+  //   if (nonRefXValueType->isRealType())
+  //     return GetCladArrayRefOfType(yType);
+  //   else
```
Comment (vgvassilev) [inline lib/Differentiator/ReverseModeVisitor.cpp:2825]: Do we need this commented code here?

File: lib/Differentiator/ReverseModeVisitor.cpp [hunk 2]
```diff
@@ -2883,12 +2820,18 @@ namespace clad {
...
       return GetCladArrayRefOfType(nonRefXValueType);
   }
 
+  clang::QualType ReverseModeVisitor::ComputeAdjointType(clang::QualType T) {
```
Comment (vgvassilev) [inline lib/Differentiator/ReverseModeVisitor.cpp:2829]: Can we add documentation describing why we remove the `const` qualification here?

File: test/Hessian/ArrayErrors.C [hunk 3]
```diff
@@ -3,7 +3,7 @@
 #include "clad/Differentiator/Differentiator.h"
 
 //CHECK-NOT: {{.*error|warning|note:.*}}
-
+//XFAIL:*
```
Comment (vgvassilev) [inline test/Hessian/ArrayErrors.C:6]: Why this starts to fail now? Worth a comment?

**Review by vgvassilev — COMMENTED** [review]
Good work. Should we add a test for CUDA if that patch improves the current state?

File: test/Hessian/ArrayErrors.C (hunk 3 above)
Comment (parth-07) [reply test/Hessian/ArrayErrors.C:6]: This PR has made the change that the adjoint type will only depend on `x` value (`x` from `dy/dx` terminology). 

The hessian mode requires that all derivative parameter types are the same irrespective of the original parameter types. This worked well with the original approach, which used to compute adjoint types solely based on the type of the return value. An example of hessian mode derived function is as follows: 

```cpp
double fn(int a, double b, long double c) { ... }
```

Hessian derived function of `fn` will have the following signature:

```cpp
void fn_hessian(int a, double b, long double c, clad::array_ref<double> hessianMatrix) { ... }
```

Here please note that derived types need to be the same for all the parameters. The change in this PR breaks this requirement, and I have thus marked the test as `XFAIL`. We can easily fix this by adding special behaviour for hessian mode, but I think that change should be in a separate PR.

Comment (vgvassilev) [reply test/Hessian/ArrayErrors.C:6]: I will merge this PR now, but please open an issue for this to be able to keep track of it.

**Review by vgvassilev — APPROVED** [review]
LGTM, modulo the comment.
