### PR TITLE
Corrected the wrong scope of the variables declared inside the Lambda function

### LINKED ISSUE #1701: FIx global variables being emmited to the outer function when visiting lambda
When differentiating
```cpp
void f2(double i, double j) {
  auto _f = [] () {
    {
      double a = 1;
    }
  };
}
```

we get

```cpp
void f2_grad(double i, double j, double *_d_i, double *_d_j) {
    double _d_a = 0.;
    double a = 0.;
    auto _f0 = []() {
        {
            double a = 1;
        }
    };
    auto _d__f = []() {
        {
            a = 1;
        }
        {
        }
    };
}
```

`double a = 0.;` declaration is in the wrong place. The fix is to make `m_Globals` a stack.

### PR DESCRIPTION
**Pull request by Vedant2005goyal**
Rather than changing the data structure of the m_Globals to stack which has been specified by the author of the issue (since it breaks the memory layout of the class) I have opted to specifically fix the variable scope problem for the Lambda functions only, by swapping the variables  in order to temporarily isolate the lambda variable declaration from the outer function and inject them in the correct scope only.
```cpp
void f2_grad(double i, double j, double *_d_i, double *_d_j) {
    auto _f0 = []() {
        {
            double a = 1;
        }
    };
    auto _d__f = []() {
        double _d_a = 0.;
        double a = 0.;
        {
            a = 1;
        }
        {
        }
    };
}
```
Fixes #1701

### CODE REVIEW

File: lib/Differentiator/ReverseModeVisitor.cpp [hunk 1]
```diff
@@ -1834,6 +1836,19 @@ Expr* ReverseModeVisitor::getStdInitListSizeExpr(const Expr* E) {
 
     CompoundStmt* DerivedBody = endBlock();
 
+    if (!m_Globals.empty()) {
+      llvm::SmallVector<Stmt*, 32> NewBodyStmts;
+      NewBodyStmts.append(m_Globals.begin(), m_Globals.end());
+      NewBodyStmts.append(DerivedBody->body().begin(),
+                          DerivedBody->body().end());
```
Comment (vgvassilev) [inline lib/Differentiator/ReverseModeVisitor.cpp:1843]: We will need tests. Can you also look why valgrind fails for this code quite badly: https://github.com/vgvassilev/clad/pull/1707

Comment (Vedant2005goyal) [reply lib/Differentiator/ReverseModeVisitor.cpp:1843]: Hi @vgvassilev 
I have identified the valgrind fail and that was due to a logical problem in the **VisitLambdaExpr** where the pop_back() operation was done without checking whether the list was empty or not and i have added a guard for that and it resolves it in my latest push.
I have earlier added regression test to increase coverage but it failed many tests due to the clang version problem which is caused by the 'if guard in the **buildDerivedLambda**'

Image

Comment (vgvassilev) [reply lib/Differentiator/ReverseModeVisitor.cpp:1843]: This should probably be a separate pull request.

Comment (Vedant2005goyal) [reply lib/Differentiator/ReverseModeVisitor.cpp:1843]: Just for clarification i want to know whether you are referring to seperate PR for the clang version thing and if yes then i will be happy to contribute to that, but for the time being should we wait for it to be merged first before proceeding with this current one?

Comment (vgvassilev) [reply lib/Differentiator/ReverseModeVisitor.cpp:1843]: I meant the valgrind fix.

Comment (Vedant2005goyal) [reply lib/Differentiator/ReverseModeVisitor.cpp:1843]: Ok I will make separate PR for that

Comment (Vedant2005goyal) [reply lib/Differentiator/ReverseModeVisitor.cpp:1843]: Hi @vgvassilev 
I have seperated the PR's, if there is anything needed to be done further, Please let me know.

Comment (vgvassilev) [reply lib/Differentiator/ReverseModeVisitor.cpp:1843]: Thank you, it has fixed the valgrind issues with llvm21 coming from lambda functions. There are a few new ones that need to be addressed but that's probably outside of the scope of this PR. To move forward this PR we need to add tests covering the newly added lines.

Comment (Vedant2005goyal) [reply lib/Differentiator/ReverseModeVisitor.cpp:1843]: Thank you @vgvassilev for reviewing the PR.

I have added the regression test covering the new lambda scope logic. Since this specific lambda behavior relies on newer Clang features, I wrapped the test case in a #if CLANG_VERSION_MAJOR > 16 guard.

Comment (vgvassilev) [reply lib/Differentiator/ReverseModeVisitor.cpp:1843]: You can do `// UNSUPPORTED: clang-13, ..., clang-15

Comment (Vedant2005goyal) [reply lib/Differentiator/ReverseModeVisitor.cpp:1843]: Use of //UNSUPPORTED was a much cleaner option! I have pushed the update.
