### PR TITLE
Don't allow non-differentiable non-const array parameters in forward mode

### LINKED ISSUE #1035: Unnecessary warning when differentiating a function that mutates its array arg
```
double example(double x, double *y)
{
    y[0] = 3;
    return x * y[0];
}

int main()
{
    double x = 10.0;
    double y[3] = {7.0, 4.6, 6.3};
    auto ex = clad::differentiate(example, "x");
    ex.dump();
    std::cout << ex.execute(x, y) << std::endl;
}
``` 
on Clad version 1.8~dev this gives a compilation warning: 
```
warning: derivative of an assignment attempts to assign to unassignable expr, assignment ignored
    y[0] = 3;
           ^
1 warning generated.
``` 
This warning is a little confusing and could be interpreted as the code not working as intended, when in reality it produces expected results.

### PR DESCRIPTION
**Pull request by PetroZarytskyi**
All parameters w.r.t. which we don't differentiate still require adjoints. Since the user doesn't provide it, we have to construct it ourselves. However, if the parameter is a pointer array (e.g., `double*`), we don't know its size and, therefore, cannot initialize the adjoint.
If the array is const, it's guaranteed that it doesn't require an adjoint. If it's a const array (e.g., `double[3]`), we can initialize it. In other cases, we have to produce an error. We've been doing the same in the reverse mode for a while.

Fixes #1035.

### CODE REVIEW

File: benchmark/BenchmarkedFunctions.h [hunk 1]
```diff
@@ -41,7 +41,7 @@ inline double product(double p[], int n) {
 }
 
 ///\returns the weighted sum of the elements in \p
-inline double weightedSum(double p[], double w[], int n) {
+inline double weightedSum(const double p[], const double w[], int n) {
```
[the remark this answers is not in the document]
Comment (PetroZarytskyi) [reply benchmark/BenchmarkedFunctions.h:44]: We shouldn't change demos

File: lib/Differentiator/BaseForwardModeVisitor.cpp [hunk 2]
```diff
@@ -317,16 +317,34 @@ void BaseForwardModeVisitor::GenerateSeeds(const clang::FunctionDecl* dFD) {
...
+    } else if (utils::isArrayOrPointerType(dParamType)) {
+      // We cannot initialize a pointer array adjoint ourselves.
+      // Produce an error.
+      if (param != m_IndependentVar &&
+          !utils::GetValueType(dParamType).isConstQualified()) {
+        diag(DiagnosticsEngine::Error, param->getLocation(),
+             "Non-differentiable non-const pointer and array parameters "
+             "are not supported. Please differentiate w.r.t. '%0' or mark "
+             "it const.",
+             {param->getNameAsString()});
```
Comment (vgvassilev) [inline lib/Differentiator/BaseForwardModeVisitor.cpp:345]:
```suggestion
        diag(DiagnosticsEngine::Error, param->getLocation(),
             "non-differentiable non-const pointer or array parameters are not supported; "
     "differentiate with respect to '%0' or mark it 'const'") << param;
```

We can create a fixit, too. Please take a look at #1596 how we should be doing diagnostics.

Comment (PetroZarytskyi) [reply lib/Differentiator/BaseForwardModeVisitor.cpp:345]: I added a fixme. I will address that in #1596
