### PR TITLE
Fix #1677 and add tests

### LINKED ISSUE #1677: Derivative tries to access wrong member of class
The internal derivative code tries to access the wrong members of a class.

Reproducer:
```
#include "clad/Differentiator/Differentiator.h"
typedef float Ffloat;
struct FphysFlow {};
typedef enum { a } b;
struct c {
  int mesh;
  int data;
};
void d(FphysFlow *i) {}
void e(b, c *p2, FphysFlow *j, Ffloat) {
  p2->data;
  d(j);
  p2->mesh;
  int f;
}
Ffloat g;
void h() {
  e(a, 0, 0, g);
  clad::gradient<clad::disable_tbr>(h);
}
```

Error:
```
test.cpp:11:7: warning: expression result unused [-Wunused-value]
   11 |   p2->data;
      |   ~~  ^~~~
test.cpp:13:7: warning: expression result unused [-Wunused-value]
   13 |   p2->mesh;
      |   ~~  ^~~~
test.cpp:19:3: error: attempted to differentiate function with no parameters
   19 |   clad::gradient<clad::disable_tbr>(h);
      |   ^~~~
error: no member named 'data' in 'FphysFlow'
test.cpp:1:1: error: cannot initialize a parameter of type 'FphysFlow *' with an lvalue of type 'Ffloat' (aka 'float')
    1 | #include "clad/Differentiator/Differentiator.h"
      | ^
test.cpp:1:1: note: passing argument to parameter '_d_i' here
error: no member named 'mesh' in 'FphysFlow'
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /bin/clang++ -fno-crash-diagnostics -fplugin=/home/msagebaum/Applications/clad/inst/lib64/clad.so -I/home/msagebaum/Applications/clad/inst/include -Xclang -plugin-arg-clad -Xclang -fgenerate-source-file -DCLAD_NO_NUM_DIFF -I/home/msagebaum/Kaiserslautern/mtu/Programms/trace_suite/trace/INCLUDE -I/home/msagebaum/Kaiserslautern/mtu/Programms/trace_suite/build_jacobian_linear_dbg/trace -I/home/msagebaum/Applications/build/include -I/usr/include/openmpi-x86_64/ -I/home/msagebaum/Kaiserslautern/mtu/Programms/trace_suite/trace/AD -I/home/msagebaum/Kaiserslautern/mtu/Programms/trace_suite/contrib/ad_dependencies/adToolbox/include test.cpp -c -o test.o -DNDEBUG -DSIMD_STRUCTS
1.	<eof> parser at end of file
 #0 0x00007f303fa2917a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib64/libLLVM.so.20.1+0x22917a)
 #1 0x00007f303fa26104 llvm::sys::RunSignalHandlers() (/lib64/libLLVM.so.20.1+0x226104)
 #2 0x00007f303f93f8f4 (/lib64/libLLVM.so.20.1+0x13f8f4)
 #3 0x00007f303f228070 __restore_rt (/lib64/libc.so.6+0x1a070)
 #4 0x00007f303e6b795c clang::Expr::getType() const /usr/include/clang/AST/Expr.h:142:37
 #5 0x00007f303e8feedd clad::ReverseModeForwPassVisitor::DifferentiateVarDecl(clang::VarDecl const*, bool) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeForwPassVisitor.cpp:277:50
 #6 0x00007f303e920b7f clad::ReverseModeVisitor::VisitDeclStmt(clang::DeclStmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeVisitor.cpp:3093:18
 #7 0x00007f303e9018cf clang::StmtVisitorBase<llvm::make_const_ptr, clad::ReverseModeVisitor, clad::StmtDiff>::Visit(clang::Stmt const*) /usr/include/clang/AST/StmtNodes.inc:1610:1
 #8 0x00007f303e8ff3ae clad::ReverseModeVisitor::Visit(clang::Stmt const*, clang::Expr*) /home/msagebaum/Applications/clad/include/clad/Differentiator/ReverseModeVisitor.h:129:11
 #9 0x00007f303e8fe71d clad::ReverseModeForwPassVisitor::ProcessSingleStmt(clang::Stmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeForwPassVisitor.cpp:192:17
#10 0x00007f303e8fe7e1 clad::ReverseModeForwPassVisitor::VisitCompoundStmt(clang::CompoundStmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeForwPassVisitor.cpp:201:29
#11 0x00007f303e901928 clang::StmtVisitorBase<llvm::make_const_ptr, clad::ReverseModeVisitor, clad::StmtDiff>::Visit(clang::Stmt const*) /usr/include/clang/AST/StmtNodes.inc:1634:1
#12 0x00007f303e8ff3ae clad::ReverseModeVisitor::Visit(clang::Stmt const*, clang::Expr*) /home/msagebaum/Applications/clad/include/clad/Differentiator/ReverseModeVisitor.h:129:11
#13 0x00007f303e8fd16f clad::ReverseModeForwPassVisitor::Derive() /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeForwPassVisitor.cpp:70:25
#14 0x00007f303e74ac1b clad::DerivativeBuilder::Derive(clad::DiffRequest const&) /home/msagebaum/Applications/clad/lib/Differentiator/DerivativeBuilder.cpp:568:18
#15 0x00007f303e41da37 clad::plugin::CladPlugin::ProcessDiffRequest(clad::DiffRequest&) /home/msagebaum/Applications/clad/tools/ClangPlugin.cpp:323:52
#16 0x00007f303e41ef6e clad::plugin::CladPlugin::FinalizeTranslationUnit() /home/msagebaum/Applications/clad/tools/ClangPlugin.cpp:536:11
#17 0x00007f303e41fd44 clad::plugin::CladPlugin::HandleTranslationUnit(clang::ASTContext&) /home/msagebaum/Applications/clad/tools/ClangPlugin.cpp:577:9
#18 0x00007f304a95e2ec clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) (/lib64/libclang-cpp.so.20.1+0x295e2ec)
#19 0x00007f3048212d49 clang::ParseAST(clang::Sema&, bool, bool) (/lib64/libclang-cpp.so.20.1+0x212d49)
#20 0x00007f304a9191af clang::FrontendAction::Execute() (/lib64/libclang-cpp.so.20.1+0x29191af)
#21 0x00007f304a87ba24 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/lib64/libclang-cpp.so.20.1+0x287ba24)
#22 0x00007f304a9accee clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/lib64/libclang-cpp.so.20.1+0x29accee)
#23 0x000055a3f3d19695 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/bin/clang+++0xa695)
#24 0x000055a3f3d15727 (/bin/clang+++0x6727)
#25 0x00007f304a41c0ad (/lib64/libclang-cpp.so.20.1+0x241c0ad)
#26 0x00007f303f93f600 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/lib64/libLLVM.so.20.1+0x13f600)
#27 0x00007f304a41b965 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (/lib64/libclang-cpp.so.20.1+0x241b965)
#28 0x00007f304a3d7bf9 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/lib64/libclang-cpp.so.20.1+0x23d7bf9)
#29 0x00007f304a3d7eb7 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/lib64/libclang-cpp.so.20.1+0x23d7eb7)
#30 0x00007f304a3faa09 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/lib64/libclang-cpp.so.20.1+0x23faa09)
#31 0x000055a3f3d14b54 clang_main(int, char**, llvm::ToolContext const&) (/bin/clang+++0x5b54)
#32 0x000055a3f3d249a8 main (/bin/clang+++0x159a8)
#33 0x00007f303f211575 __libc_start_call_main (/lib64/libc.so.6+0x3575)
#34 0x00007f303f211628 __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x3628)
#35 0x000055a3f3d12e05 _start (/bin/clang+++0x3e05)
clang++: error: clang frontend command failed with exit code 139 (use -v to see invocation)
```

Command line:
```
/bin/clang++ -fno-crash-diagnostics -fplugin=/home/msagebaum/Applications/clad/inst/lib64/clad.so -I/home/msagebaum/Applications/clad/inst/include -Xclang -plugin-arg-clad -Xclang -fgenerate-source-file -DCLAD_NO_NUM_DIFF test.cpp -c -o test.o
```

### PR DESCRIPTION
**Pull request by PetroZarytskyi**
This PR fixes 2 bugs that pop out in #1677, and adds a new test file for them.
Fixes #1677.

### CODE REVIEW

File: test/Gradient/ReverseForw.C [hunk 1]
```diff
@@ -0,0 +1,129 @@
+// RUN: %cladclang %s -I%S/../../include -oReverseForw.out 2>&1 | %filecheck %s
```
Comment (vgvassilev) [inline test/Gradient/ReverseForw.C:1]: If this fixes a particular issue in the tracker why not having it as `issue-xxx.cpp`?

Comment (vgvassilev) [reply test/Gradient/ReverseForw.C:1]: Okay, I see this is shared between two issues -- we are all good.

**Review by vgvassilev — APPROVED** [review]
LGTM!
