### PR TITLE
A reverse block is never ended in RMV::VisitConditionalStatement

### LINKED ISSUE #922: Regression in `clad` master in dealing with templated functions
This was noticed when running the RooFit unit tests with clad `master`.

Reproducer (ROOT macro, but should be easy to turn into compiled executable):
```c++
template <bool pdfMode>
inline double polynomial(double const *coeffs, int nCoeffs, int lowestOrder, double x)
{
   double retVal = coeffs[nCoeffs - 1];
   for (int i = nCoeffs - 2; i >= 0; i--)
      retVal = coeffs[i] + x * retVal;
   retVal = retVal * std::pow(x, lowestOrder);
   return retVal + (pdfMode && lowestOrder > 0 ? 1.0 : 0.0);
}

double roo_func_wrapper_4(double *params)
{
   double t4[] = {params[0], params[1], 1.};
   const double t5 = polynomial<false>(t4, 3, 0, 1.);
   return t5;
}
#include <Math/CladDerivator.h>

#pragma clad ON
void roo_func_wrapper_4_req()
{
   clad::gradient(roo_func_wrapper_4, "params");
}
#pragma clad OFF

void reproducer()
{
   std::vector<double> parametersVec = {-0.5, -0.5, 0.5};

   std::vector<double> gradientVec(parametersVec.size());

   auto wrapper = [&](double *params) { return roo_func_wrapper_4(params); };

   std::cout << roo_func_wrapper_4(parametersVec.data()) << std::endl;
   roo_func_wrapper_4_grad(parametersVec.data(), gradientVec.data());

   std::cout << "Clad diff:" << std::endl;
   std::cout << gradientVec[0] << std::endl;
   std::cout << gradientVec[1] << std::endl;
   std::cout << gradientVec[2] << std::endl;

   auto numDiff = [&](int i) {
      const double eps = 1e-6;
      std::vector<double> p{parametersVec};
      p[i] = parametersVec[i] - eps;
      double nllValDown = wrapper(p.data());
      p[i] = parametersVec[i] + eps;
      double nllValUp = wrapper(p.data());
      return (nllValUp - nllValDown) / (2 * eps);
   };

   std::cout << "Num diff:" << std::endl;
   std::cout << numDiff(0) << std::endl;
   std::cout << numDiff(1) << std::endl;
   std::cout << numDiff(2) << std::endl;
}
```

Output:
```txt
0
Clad diff:
0
0
0
Num diff:
1
1
0
```

### PR DESCRIPTION
**Pull request by PetroZarytskyi**
This PR fixed a bug when a reverse block was never ended in ``RMV::VisitConditionalStatement``. This is the root cause of the problem mentioned in #922.
Fixes #922.

### CODE REVIEW

File: lib/Differentiator/ReverseModeVisitor.cpp [hunk 1]
```diff
@@ -945,20 +945,20 @@ Expr* getArraySizeExpr(const ArrayType* AT, ASTContext& context,
                          .get();
     // If result is a glvalue, we should keep it as it can potentially be
     // assigned as in (c ? a : b) = x;
```
Comment (vaithak) [inline lib/Differentiator/ReverseModeVisitor.cpp:947]: Can we add the test mentioned in the issue?

**Review by vaithak — APPROVED** [review]
LGTM.
I think we can squash the commits together, and maybe have a better PR message.
Maybe "Ensure proper ending of the reverse block for conditional statements."
Please ensure that the example that Jonas posted is working.

File: lib/Differentiator/ReverseModeVisitor.cpp (hunk 1 above)
Comment (PetroZarytskyi) [reply lib/Differentiator/ReverseModeVisitor.cpp:947]: Done.

**Comment by PetroZarytskyi** [comment]
@vaithak I just ran the example and it works:
```
Clad diff:
1
1
0
Num diff:
1
1
0
```
