### PR TITLE
Fix call expr to functor inside a function

### LINKED ISSUE #625: Failure in differentiating call expression to a function object
Results in the following assertion failure:
```
ReverseModeVisitor.cpp:1463: clad::StmtDiff clad::ReverseModeVisitor::VisitCallExpr(const clang::CallExpr*): Assertion `!utils::isArrayOrPointerType(arg->getType()) && "Arguments passed by pointers should be covered in pass by " "reference calls"' failed.
```

Minimal reproducible example (taken from https://github.com/vgvassilev/clad/discussions/618) :
```cpp
# include "clad/Differentiator/Differentiator.h"
# include <iostream>

struct FunObj {
   double operator()(double *x, size_t n)
   {  double ret = 0;
      for (size_t i = 0; i < n; i++) {
         ret += (i+1) * x[i];
      }
      return ret;
   }
};

double f(double *x, size_t n){
  FunObj f_obj;
  return f_obj(x, n);
}

int main() {
   size_t n = 3;
   double x[] = {1.0, 2.0, 3.0};
   double fx = f(x, n);
   std::cout << "f(x, n) = " << fx << "\n";

   auto f_dx = clad::gradient(f, "x");
   double dx[] = {0.0, 0.0, 0.0};
   clad::array_ref<double> dx_ref(dx, n);
   f_dx.execute(x, n, dx_ref);

   for(size_t i = 0; i < n; ++i)
      std::cout << "df/dx[" << i << "] = " << dx[i] << "\n";
   return 0;
}
```

### PR DESCRIPTION
**Pull request by vaithak**
This fixes #625 for the case when a functor is indirectly differentiated because of a call expression inside a function.

### CODE REVIEW

**Review by vgvassilev — APPROVED** [review]
LGTM!

File: lib/Differentiator/ReverseModeVisitor.cpp [hunk 1]
```diff
@@ -1412,12 +1413,20 @@ Expr* getArraySizeExpr(const ArrayType* AT, ASTContext& context,
     // statements there later.
     std::size_t insertionPoint = getCurrentBlock(direction::reverse).size();
 
+    // `CXXOperatorCallExpr` have the `base` expression as the first argument.
+    size_t skipFirstArg = 0;
```
Comment (parth-07) [inline lib/Differentiator/ReverseModeVisitor.cpp:1417]: Apologies for the late review.

What is the main issue if we do not skip the first arg? I suppose it might be required if we modify the functor's member variables in the call operator.

Comment (vaithak) [reply lib/Differentiator/ReverseModeVisitor.cpp:1417]: The first arg in the operator call is the base expression, I used the logic of skipping the first arg from this in forward mode: https://github.com/vgvassilev/clad/blob/master/lib/Differentiator/BaseForwardModeVisitor.cpp#L980
