### PR TITLE
Fix Incorrect derivative when loops contains continue

### LINKED ISSUE #710: Incorrect derivative when loops contains `continue`
Reproducible example:
```cpp
#include "clad/Differentiator/Differentiator.h"
#include <iostream>

#define show(x) std::cout << #x << ": " << x << "\n";

double fn(double u, double v) {
    double res = 11 * u;
    for (int i = 0; i < 3; i++) {
        res += u * i;
        continue;
    }
    return res;
}

int main() {
    auto d_fn = clad::gradient(fn);
    double u = 3, v = 5;
    double du, dv;
    du = dv = 0;
    d_fn.execute(u, v, &du, &dv);
    show(du);
    show(dv);
}
```

**Output**
du: 20
dv: 0

**Expected output**
du: 14
dv: 0

### LINKED ISSUE #851: Don't increment the for loop variable when there's a break statement
Due to PR #833, the step of the for loop variable is performed for every branch case of the for loop. However, when there's a break statement in the for loop, the step is not applied afterwards, which isn't the case when there's a continue statement or neither of them. So we shouldn't increment the variable beforehand in this case.

Example:
```cpp
#include "clad/Differentiator/Differentiator.h"
#include <iostream>

#define show(x) std::cout << #x << ": " << x << "\n";

double fn(double u, double v) {
    double res = 0;
    for (int i = 1; i < 3; i++) {
        res += i * u;
        if (i == 1)
            break;
    }
    return res;
}

int main() {
    auto d_fn = clad::gradient(fn);
    double u = 3, v = 5;
    double du, dv;
    du = dv = 0;
    d_fn.execute(u, v, &du, &dv);
    show(du);
    show(dv);
}
```
Expected output:
**du** = 3
**dv** = 0

Output:
**du** = 0
**dv** = 0

### PR DESCRIPTION
**Pull request by kchristin22**
For more details please see https://github.com/vgvassilev/clad/issues/710#issuecomment-2007143504. This PR concerns only the fix of #710, so the only change needed is the one regarding the position of  the step of the forward loop's variable in the reverse pass. Tests need to be updated accordingly if the change is approved.

Closes #710, closes #851.

### CODE REVIEW

File: lib/Differentiator/ReverseModeVisitor.cpp [hunk 1]
```diff
@@ -3529,6 +3529,10 @@ Expr* getArraySizeExpr(const ArrayType* AT, ASTContext& context,
       bodyDiff.updateStmtDx(MakeCompoundStmt(revLoopBlock));
     m_LoopBlock.pop_back();
 
+    activeBreakContHandler->EndCFSwitchStmtScope();
+    activeBreakContHandler->UpdateForwAndRevBlocks(bodyDiff);
+    PopBreakContStmtHandler();
+    
     // Increment statement in the for-loop is only executed if the iteration
```
Comment (parth-07) [inline lib/Differentiator/ReverseModeVisitor.cpp:3536]: Please update this comment.

**Review by parth-07 — CHANGES_REQUESTED** [review]
Thank you for the pull-request. The solution seems good. Can you please add tests and update the pull-request description?

Also, can you please open an issue regarding fixing incorrect derivatives when loops contains `break`? You can use this test case:

```cpp
#include "clad/Differentiator/Differentiator.h"
#include <iostream>

#define show(x) std::cout << #x << ": " << x << "\n";

double fn(double u, double v) {
    double res = 0;
    for (int i = 1; i < 3; i++) {
        res += i * u;
        if (i == 1)
            break;
    }
    return res;
}

int main() {
    auto d_fn = clad::gradient(fn);
    double u = 3, v = 5;
    double du, dv;
    du = dv = 0;
    d_fn.execute(u, v, &du, &dv);
    show(du);
    show(dv);
}
```

**Comment by kchristin22** [comment]
I will update the tests, the description and the comment.

> Also, can you please open an issue regarding fixing incorrect derivatives when loops contains break? You can use this test case:

Sure thing!

**Comment by kchristin22** [comment]
Upon checking out the above example, the error occurs after the change of this PR right? I noticed that the decrement of i-- should be after the switch case when there's a break stmt as otherwise we "miss" a value of i. I will open a new PR for the new issue.

**Comment by parth-07** [comment]
>  the error occurs after the change of this PR right? 

Yes, however, the `break` statement had incorrect behavior without this PR change as well. It's just that the particular example that I added happen to work for Clad on master.

> I noticed that the decrement of i-- should be after the switch case when there's a break stmt as otherwise we "miss" a value of i.

In the case of a `break` statement, the last increment does not happen. So we need to skip the corresponding decrement as well when the `break` statement is hit.

**Comment by kchristin22** [comment]
I have not forgotten this. I will update it in the upcoming week. Sorry for the delay.

**Review by parth-07 — CHANGES_REQUESTED** [review]
Can you please add a test case where Clad was giving incorrect derivative result before?

**Comment by kchristin22** [comment]
@parth-07 I tried to add a new function in Loops.C, but even though I get the correct result when I compile locally this file and run it, somehow when I test using `make check-clad`, the result is expected to be 15.00 and if I change that to 15.00 it then says that the result of fn21 is expected to be 7.00 (which is correct). The fn21_grad function printed as a log due to the error also doesn't match the one that was checked and succeeded.

**Review by parth-07 — CHANGES_REQUESTED** [review]
Can you please add tests as well?

**Comment by kchristin22** [comment]
> Can we undo the formatting changes which are not related to the changes of this pr?

Yes sorry about that, I was trying to fix it, cause my local version of git-clang-format produces different results than the CI. I think now it includes only the necessary changes more or less.

**Comment by parth-07** [comment]
@kchristin22 Can you please add tests in the PR?

File: test/Gradient/Loops.C [hunk 2]
```diff
@@ -3133,6 +3142,123 @@ double fn39(double x) {
...
+//CHECK-NEXT:        }
+//CHECK-NEXT:        clad::push(_t2, {{2U|2UL}});
+//CHECK-NEXT:    }
+//CHECK-NEXT:    _d_res += 1;
+//CHECK-NEXT:    for (;; _t0--) {
+//CHECK-NEXT:        {
+//CHECK-NEXT:            if (!_t0)
+//CHECK-NEXT:                break;
+//CHECK-NEXT:        }
+//CHECK-NEXT:        if (clad::size(_t2) != 0 && clad::back(_t2) != 1)
```
Comment (parth-07) [inline test/Gradient/Loops.C:3241]: Currently, we are repeating `clad::size(_t2)` in the condition if there are multiple `break` statements in the loop. Can you modify the condition-generation code such that `clad::size(...)` does not get repeated?

Also, do we need to check this condition on each iteration? We know that if `break` is hit, then it must be hit in the last iteration of the loop. Can we use that knowledge to only evaluate this condition once?

**Review by parth-07 — CHANGES_REQUESTED** [review]

File: test/Gradient/Loops.C (hunk 2 above)
Comment (kchristin22) [reply test/Gradient/Loops.C:3241]: I guess the other solution would be to perform the reverse of the inc diff and cond diff in the forward pass as well, and perform the inc and cond diff in the reverse pass without the if check. So, it would look like a `x + a - a = x` situation. I'm not sure if that's more efficient than the if-check tbh. Maybe the compiler would be able to tell that this if condition is only true in the first iteration either way.

Comment (parth-07) [reply test/Gradient/Loops.C:3241]: > I guess the other solution would be to perform the reverse of the inc diff and cond diff in the forward pass as well, and perform the inc and cond diff in the reverse pass without the if check.

I did not mean completely changing the solution.

With this solution, the `if`-condition for decrementing the counter variable when there are 2 break statements in the primal `for`-loop is as:

```cpp
 if (clad::size(_t2) != 0 && clad::back(_t2) != 1 && clad::size(_t2) != 0 && clad::back(_t2) != 2)
    i--;
```
This `if`-statement is evaluated per iteration of the for-loop. All the conditions in the `if`-statement needs to be evaluated for the common case where the iteration does not correspond to hitting `break` statement. That's 4 expression evaluations per iteration. We know that a `break` expression can only be hit once for a given loop, and if it is indeed hit, it is hit in the last iteration of the loop. Can we use this knowledge to optimize the solution? 

One way might be:

```cpp
 for (size numIterations = _t0;; _t0--) {
  {
    if (!_t0)
    break;
  }

  // if (clad::size(_t2) != 0 && clad::back(_t2) != 1 && clad::size(_t2) != 0 && clad::back(_t2) != 2)
  //   i--;
  // Instead of the above if-statement, we can have:
  if (_t0 != numIterations || (clad::back(_t2) != 1 || clad::back(_t2) != 2))
    i--;
  
  // ... remaining loop will be exactly the same as before ...
  // ...
  // ..
}
```
With this solution, `if`-statement will check for `break` statements counter only for the last iteration. For all other iterations, only one condition in the `if`-statement is evaluated.

Comment (kchristin22) [reply test/Gradient/Loops.C:3241]: I understood what you said, it just didn't go with the current formation of the for-loop (there's no `numIterations` currently), so I wasn't sure if you meant adding that or examine another possibility.

I'll see if I can add it easily.

Comment (kchristin22) [reply test/Gradient/Loops.C]: I did it, let me know if there are any new comments @parth-07

File: test/Gradient/Loops.C [hunk 3]
```diff
@@ -3133,6 +3142,123 @@ double fn39(double x) {
...
+//CHECK-NEXT:        }
+//CHECK-NEXT:        clad::push(_t2, {{2U|2UL}});
+//CHECK-NEXT:    }
+//CHECK-NEXT:    _d_res += 1;
+//CHECK-NEXT:    for (unsigned {{int|long}} _numRevIterations0 = _t0; ; _t0--) {
+//CHECK-NEXT:        {
+//CHECK-NEXT:            if (!_t0)
+//CHECK-NEXT:                break;
+//CHECK-NEXT:        }
+//CHECK-NEXT:        if (_t0 != _numRevIterations0 || (clad::size(_t2) != 0 && clad::back(_t2) != 1))
```
Comment (parth-07) [inline test/Gradient/Loops.C:3241]: We don't need `clad::size()` expression now in the `if`-statement.

**Review by parth-07 — CHANGES_REQUESTED** [review]

File: test/Gradient/Loops.C (hunk 3 above)
Comment (kchristin22) [reply test/Gradient/Loops.C:3241]: It is generally needed in order to ensure that cases like fn17 are covered, where the the tape containing the break path is empty

Comment (parth-07) [reply test/Gradient/Loops.C:3241]: Do you mean this function?
```cpp
double fn17(double i, double j) {
  int counter = 5;
  double res = 0;
  for (int ii=0; ii<counter; ++ii) {
    int jj = ii;
    if (ii < 2)
      continue;
    while (jj--) {
      if (jj < 3) {
        res += i*j;
        break;
      } else {
        continue;
      }
      res += i*i*j*j;
    }
  }
  return res;
}
```

> where the the tape containing the break path is empty

What do you mean by the tape is empty for the break path?

Comment (kchristin22) [reply test/Gradient/Loops.C]: You actually pointed me to a bug! I forgot to refresh the current break flag when visiting a while or do-while loop so in fn17 f.i., for the outer loop decrement, I checked if it was the break path of the inside loop which ofc wasn't necessary and also the inner loop had different iterations than the outer loop, so the tape for the inside loop had less entries, causing an error when its size wasn't checked before trying to read its last value. I fixed it now and removed the size expr.

**Review by parth-07 — APPROVED** [review]
Looks good.

File: test/Gradient/Loops.C (hunk 3 above)
Comment (parth-07) [reply test/Gradient/Loops.C]: Okay, sounds good.
