### PR TITLE
Make built-in type variable declarations global

### LINKED ISSUE #681: Regression with Clad `master` in case of num-diff fallback in specific conditions
Some of the RooFit tests are still failing with Clad `master`, because of code that hits very specific conditions.

To reproduce the underlying problem, first create a library with any function:
```c++
// clang++ -fPIC mylib.cxx -c -o mylib.o && ar r libmylib.a mylib.o

double foo(double x, double y, double z)
{
   return x * y * z;
}
```
Then use that library in a function the is differentiated:
```c++
// Compile with clang++ -O2 -std=c++20 -fplugin=/usr/lib/clad.so repro_regression.cxx -o repro_regression -lmylib -L.

#include "clad/Differentiator/Differentiator.h"

#include <iostream>
#include <vector>

double foo(double x, double y, double z);

double wrapper(double *params)
{
   if (true) {
      double constant = 11.;
      return foo(params[0], constant, 1.);
   }

   return 0.0;
}

int main()
{
   std::vector<double> params{4};

   std::cout << "Value" << std::endl;
   const double nllVal = wrapper(params.data());
   std::cout << nllVal << std::endl;
   std::cout << std::endl;

   auto grad = clad::gradient(wrapper, "params");

   std::vector<double> gradResult(1);
   grad.execute(params.data(), gradResult.data());

   std::cout << "Clad diff:" << std::endl;
   std::cout << gradResult[0] << std::endl;
   std::cout << std::endl;

   auto numDiff = [&](int i) {
      const double eps = 1e-6;
      std::vector<double> p{params};
      p[i] = params[i] - eps;
      double nllValDown = wrapper(p.data());
      p[i] = params[i] + eps;
      double nllValUp = wrapper(p.data());
      return (nllValUp - nllValDown) / (2 * eps);
   };

   std::cout << "Num diff:" << std::endl;
   std::cout << numDiff(0) << std::endl;
}
```

Many conditions need to be met to get this Clad error:
* You need to compile with `-O2`
* You need to call a function in a library such that Clad falls back to num. diff.
* The code needs to be in a branch, like this `if (true)` in the reproducer
* One of the function variables must be a named variable (i.e., doing `foo(params[0], 11., 1.)` would not hit the bug)

The output will be:
```txt
Value
44

Clad diff:
0

Num diff:
11
```

My compiler setup:
```txt
clang version 16.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /bin
```

### PR DESCRIPTION
**Pull request by PetroZarytskyi**
When we produce a gradient function we generally have a forward and reverse
sweep. In the forward sweep we accumulate the state and in the reverse sweep
we use that state to invert the program execution. The forward sweep generally
follows the sematics of the primal function and when neccessary stores the state
which would be needed but lost for the reverse sweep.

However, to minimize the stores onto the tape we need to reuse some of the
variables between the forward and the reverse sweeps which requires some
variables to be promoted to the enclosing lexical scope of both sweeps.

Fixes https://github.com/vgvassilev/clad/issues/659, fixes https://github.com/vgvassilev/clad/issues/681.

### CODE REVIEW

**Comment by parth-07** [comment]
Why do we need both this pull request and #688?

File: lib/Differentiator/StmtClone.cpp [hunk 1]
```diff
@@ -520,8 +520,12 @@ bool ReferencesUpdater::VisitDeclRefExpr(DeclRefExpr* DRE) {
   // Replace the declaration if it is present in `m_DeclReplacements`.
   if (VarDecl* VD = dyn_cast<VarDecl>(DRE->getDecl())) {
     auto it = m_DeclReplacements.find(VD);
-    if (it != std::end(m_DeclReplacements))
+    if (it != std::end(m_DeclReplacements)) {
       DRE->setDecl(it->second);
+      if (it->second->getType().getNonReferenceType()!=DRE->getType()) {
+        DRE->setType(it->second->getType().getNonReferenceType());
+      }
+    }
```
Comment (vgvassilev) [inline lib/Differentiator/StmtClone.cpp:528]:
```suggestion
      QualType NonRefQT = it->second->getType().getNonReferenceType();
      if (NonRefQT != DRE->getType())
        DRE->setType(NonRefQT);
    }
```

Why this change was necessary? Can it go in a separate PR with a test?

File: lib/Differentiator/VisitorBase.cpp [hunk 2]
```diff
@@ -143,8 +144,10 @@ namespace clad {
       m_Sema.ActOnUninitializedDecl(VD);
     }
     m_Sema.FinalizeDeclaration(VD);
+    if (!scope)
+        scope = getCurrentScope();
```
Comment (vgvassilev) [inline lib/Differentiator/VisitorBase.cpp:148]: Why was this necessary?

File: lib/Differentiator/VisitorBase.cpp [hunk 3]
```diff
@@ -407,11 +418,19 @@ namespace clad {
   }
 
   Expr* VisitorBase::BuildArraySubscript(
-      Expr* Base, const llvm::SmallVectorImpl<clang::Expr*>& Indices) {
```
Comment (vgvassilev) [inline lib/Differentiator/VisitorBase.cpp:410]: Why dropping the const here - we are not changing the content of `Indices`.

File: lib/Differentiator/ReverseModeVisitor.cpp [hunk 4]
```diff
@@ -2752,6 +2725,9 @@ Expr* getArraySizeExpr(const ArrayType* AT, ASTContext& context,
     llvm::SmallVector<Decl*, 4> declsDiff;
     // Need to put array decls inlined.
     llvm::SmallVector<Decl*, 4> localDeclsDiff;
+    // FIXME: find a more reliable way to determine if the declaration
+    // is in the function global scope.
+    bool isInFunctionGlobalScope = m_Reverse.size() <= 2;
```
Comment (vgvassilev) [inline lib/Differentiator/ReverseModeVisitor.cpp:2730]: Can't we ask the current scope if it is a function global scope?

File: lib/Differentiator/VisitorBase.cpp (hunk 2 above)
Comment (PetroZarytskyi) [reply lib/Differentiator/VisitorBase.cpp:148]: Declarations used to always be added to the current ``clang::Scope``, even the decl stmts were added to the function global scope in the derivative. Because of this, we could, for instance, declare multiple local variables ``i`` and subsequently have multiple ``_d_i`` decl stmts in the function global scope of the derivative. Such name conflicts were not detected. With this PR, we have way more global declarations and so this became more noticeable. You can take a look at ``BuildGlobalVarDecl`` to see why I introduced these lines.

File: lib/Differentiator/StmtClone.cpp (hunk 1 above)
Comment (PetroZarytskyi) [reply lib/Differentiator/StmtClone.cpp:528]: To make ref-type declarations global, I replaced them with pointers (to allow us to separate the declaration and the initialization). However, ``VisitorBase::Clone`` didn't expect a cloned expression to have a different type than the original expression, which led to broken AST. This could go in a separate PR but it doesn't make much sense by itself.

File: lib/Differentiator/VisitorBase.cpp (hunk 3 above)
Comment (PetroZarytskyi) [reply lib/Differentiator/VisitorBase.cpp:410]: This caused an issue on some compiler versions but I fixed it without dropping const now.

File: lib/Differentiator/ReverseModeVisitor.cpp [hunk 5]
```diff
@@ -2530,19 +2516,26 @@ Expr* getArraySizeExpr(const ArrayType* AT, ASTContext& context,
   VarDeclDiff ReverseModeVisitor::DifferentiateVarDecl(const VarDecl* VD) {
     StmtDiff initDiff;
     Expr* VDDerivedInit = nullptr;
+    // We take the parent of the current scope because the main compound
```
Comment (vgvassilev) [inline lib/Differentiator/ReverseModeVisitor.cpp:2519]: If `getCurrentScope()->isFunctionScope()` is false for `int f() {` this probably means that when we create the scope for the first compound statement of the function we should also add the `Scope::FnScope` flag to the current scope.

File: lib/Differentiator/ReverseModeVisitor.cpp [hunk 6]
```diff
@@ -2752,6 +2725,9 @@ Expr* getArraySizeExpr(const ArrayType* AT, ASTContext& context,
     llvm::SmallVector<Decl*, 4> declsDiff;
     // Need to put array decls inlined.
     llvm::SmallVector<Decl*, 4> localDeclsDiff;
+    // We take the parent of the current scope because the main compound
+    // statement of the function has its own scope as well.
+    bool isInFunctionGlobalScope = getCurrentScope()->getParent()==m_DerivativeFnScope;
```
Comment (vgvassilev) [inline lib/Differentiator/ReverseModeVisitor.cpp:2730]: See past comments.

File: lib/Differentiator/ReverseModeVisitor.cpp [hunk 7]
```diff
@@ -2779,33 +2755,34 @@ Expr* getArraySizeExpr(const ArrayType* AT, ASTContext& context,
...
-              auto* assignment = BuildOp(BO_Assign, declRef, decl->getInit());
-              inits.push_back(BuildOp(BO_Comma, pushPop.getExpr(), assignment));
+        if (!isInFunctionGlobalScope) {
+          auto* decl = VDDiff.getDecl();
+          // The same variable will be assigned with new values every
+          // loop iteration so the const qualifier must be dropped.
+          if (decl->getType().isConstQualified()) {
+            QualType nonConstType =
+                getNonConstType(decl->getType(), m_Context, m_Sema);
+            decl->setType(nonConstType);
```
Comment (vgvassilev) [inline lib/Differentiator/ReverseModeVisitor.cpp:2770]: Changing the AST invariants that way is quite dangerous. Do we have a more elegant solution for future? We should add at least a bunch of tests for this case.

We should probably include perhaps a peusdo code example in the comments.

File: lib/Differentiator/ReverseModeVisitor.cpp [hunk 8]
```diff
@@ -2779,33 +2755,34 @@ Expr* getArraySizeExpr(const ArrayType* AT, ASTContext& context,
...
-                  StoreAndRestore(declRef, /*prefix=*/"_t", /*force=*/true);
-              if (pushPop.getExpr() != declRef)
-                addToCurrentBlock(pushPop.getExpr_dx(), direction::reverse);
-              auto* assignment = BuildOp(BO_Assign, declRef, decl->getInit());
-              inits.push_back(BuildOp(BO_Comma, pushPop.getExpr(), assignment));
+        if (!isInFunctionGlobalScope) {
+          auto* decl = VDDiff.getDecl();
+          // The same variable will be assigned with new values every
+          // loop iteration so the const qualifier must be dropped.
+          if (decl->getType().isConstQualified()) {
```
Comment (vgvassilev) [inline lib/Differentiator/ReverseModeVisitor.cpp:2767]:
```suggestion
          QualType DeclTy = decl->getType();
          if (DeclTy.isConstQualified()) {
```

File: lib/Differentiator/ReverseModeVisitor.cpp [hunk 9]
```diff
@@ -2779,33 +2755,34 @@ Expr* getArraySizeExpr(const ArrayType* AT, ASTContext& context,
...
+            QualType nonConstType =
+                getNonConstType(decl->getType(), m_Context, m_Sema);
+            decl->setType(nonConstType);
+          }
+          if (VD->getInit()) {
```
Comment (vgvassilev) [inline lib/Differentiator/ReverseModeVisitor.cpp:2772]: This case is also worth commenting including perhaps a peusdo code example.

File: lib/Differentiator/StmtClone.cpp (hunk 1 above)
Comment (vgvassilev) [reply lib/Differentiator/StmtClone.cpp:528]: Ok, the code suggestion still makes sense though..

File: lib/Differentiator/VisitorBase.cpp (hunk 2 above)
Comment (vgvassilev) [reply lib/Differentiator/VisitorBase.cpp:148]: Maybe that's worth a comment in the code. I am still not getting how the scope can be nullptr.

**Review by vgvassilev — COMMENTED** [review]
Glad to see moving! Here is a round of comments.

File: include/clad/Differentiator/Array.h [hunk 10]
```diff
@@ -81,6 +81,11 @@ template <typename T> class array {
   }
 
   CUDA_HOST_DEVICE array<T>& operator=(const array<T>& arr) {
+    if (m_size < arr.m_size) {
+      delete[] m_arr;
+      m_arr = new T[arr.m_size];
```
[the remark this answers is not in the document]
Comment (PetroZarytskyi) [reply include/clad/Differentiator/Array.h:87]: Done.

File: lib/Differentiator/ReverseModeVisitor.cpp (hunk 9 above)
Comment (PetroZarytskyi) [reply lib/Differentiator/ReverseModeVisitor.cpp:2790]: Done.

File: lib/Differentiator/ReverseModeVisitor.cpp [hunk 11]
```diff
@@ -1301,18 +1285,20 @@ Expr* getArraySizeExpr(const ArrayType* AT, ASTContext& context,
...
       // If current context is different than the context of the original
       // declaration (e.g. we are inside lambda), rebuild the DeclRefExpr
       // with Sema::BuildDeclRefExpr. This is required in some cases, e.g.
       // Sema::BuildDeclRefExpr is responsible for adding captured fields
       // to the underlying struct of a lambda.
       if (VD->getDeclContext() != m_Sema.CurContext)
         clonedDRE = cast<DeclRefExpr>(BuildDeclRef(VD));
-
+      if (DRE->getDecl()->getType()->isReferenceType()
+          && clonedDRE->getType()->isPointerType())
```
[the remark this answers is not in the document]
Comment (PetroZarytskyi) [reply lib/Differentiator/ReverseModeVisitor.cpp:1303]: This happens in the cases where we have to make ref-type variables global. Their clones have to become pointer-type to allow us to separate their declarations and initializations. I added a comment explaining this.

File: lib/Differentiator/ReverseModeVisitor.cpp [hunk 12]
```diff
@@ -2530,19 +2516,26 @@ Expr* getArraySizeExpr(const ArrayType* AT, ASTContext& context,
   VarDeclDiff ReverseModeVisitor::DifferentiateVarDecl(const VarDecl* VD) {
     StmtDiff initDiff;
     Expr* VDDerivedInit = nullptr;
+    // We take the parent of the current scope because the main compound
+    // statement of the function has its own scope as well.
+    bool isInFunctionGlobalScope = getCurrentScope()->getParent()==m_DerivativeFnScope;
```
[the remark this answers is not in the document]
Comment (PetroZarytskyi) [reply lib/Differentiator/ReverseModeVisitor.cpp:2524]: Because the outermost compound statement is not considered function scope.

[the remark this answers is not in the document]
Comment (PetroZarytskyi) [reply lib/Differentiator/ReverseModeVisitor.cpp]: I made the outermost compound statement FnScope so now this option works. I did this in my last commit.

File: lib/Differentiator/ReverseModeVisitor.cpp (hunk 7 above)
Comment (PetroZarytskyi) [reply lib/Differentiator/ReverseModeVisitor.cpp:2780]: What exactly is dangerous? Can you give an example of what would break this?

Comment (vgvassilev) [reply lib/Differentiator/ReverseModeVisitor.cpp:2780]: We want to only change the properties of the produced by Clad AST nodes. It seems the case here but I got confused.

File: lib/Differentiator/ReverseModeVisitor.cpp [hunk 13]
```diff
@@ -2779,33 +2763,48 @@ Expr* getArraySizeExpr(const ArrayType* AT, ASTContext& context,
...
+        if (promoteToFnScope) {
+          auto* decl = VDDiff.getDecl();
+          // The same variable will be assigned with new values every
+          // loop iteration so the const qualifier must be dropped.
+          // (look at the next comment for more details).
+          QualType DeclTy = decl->getType();
+          if (DeclTy.isConstQualified()) {
+            QualType nonConstType =
+                getNonConstType(decl->getType(), m_Context, m_Sema);
+            decl->setType(nonConstType);
```
Comment (vgvassilev) [inline lib/Differentiator/ReverseModeVisitor.cpp:2792]: Is codecov right that we do not have a test for this?

Comment (PetroZarytskyi) [reply lib/Differentiator/ReverseModeVisitor.cpp]: I got confused. This procedure is already done earlier. I removed this bit.

**Review by vgvassilev — APPROVED** [review]
LGTM! Good job!
