### PR TITLE
Remove static asserts from generated code

### LINKED ISSUE #700: Clang segfaults for program using header <random>
**Minimal example**:
```c++
#include <random>
#include "clad/Differentiator/Differentiator.h"

double f(double x){
  std::mt19937 gen64;
  std::uniform_real_distribution<double> distribution(0.0,1.0);
  double rand = distribution(gen64);
  return x+rand;
}

int main(){
  auto f_dx = clad::differentiate(f, "x");
  f_dx.execute(3.14);
}
```

**Expected behaviour**: Code compiles. The derivative should evaluate to 1.

**Observed behaviour**: Clang segfaults.

**Setup**: Clad built from the GitHub master branch at commit 7449329197788a4ba523b179479d2483b66b12b8 on Ubuntu 22.04 with Clang 11. The segfault appears both with the GCC 12 libstdc++ and with the LLVM-11 libc++ (`-stdlib=libc++`).

**Further information**: The analogous code used to crash for Enzyme (EnzymeAD/Enzyme#1600), but likely for a different reason (missing support for `long double` in C++ header `<random>`), which has been fixed in EnzymeAD/Enzyme#1604.

### PR DESCRIPTION
**Pull request by vaithak**
fixes #700 (partially - for fwd mode) , #849

### CODE REVIEW

File: lib/Differentiator/BaseForwardModeVisitor.cpp [hunk 1]
```diff
@@ -1454,6 +1453,8 @@ StmtDiff BaseForwardModeVisitor::VisitDeclStmt(const DeclStmt* DS) {
         m_DeclReplacements[VD] = VDDiff.getDecl();
       decls.push_back(VDDiff.getDecl());
       declsDiff.push_back(VDDiff.getDecl_dx());
+    } else if (auto SAD = dyn_cast<StaticAssertDecl>(D)) {
+      return VisitStaticAssertDecl(SAD);
```
Comment (vgvassilev) [inline lib/Differentiator/BaseForwardModeVisitor.cpp:1457]: Isn't here the problem that we do not call `Visit` of `D` in the very first line of the loop?

Comment (vaithak) [reply lib/Differentiator/BaseForwardModeVisitor.cpp]: fixed and made it more generic 👍🏼

File: lib/Differentiator/BaseForwardModeVisitor.cpp [hunk 2]
```diff
@@ -2022,4 +2023,9 @@ StmtDiff BaseForwardModeVisitor::VisitSubstNonTypeTemplateParmExpr(
     const clang::SubstNonTypeTemplateParmExpr* NTTP) {
   return Visit(NTTP->getReplacement());
 }
+
+StmtDiff BaseForwardModeVisitor::VisitStaticAssertDecl(
+    const clang::StaticAssertDecl* SAD) {
+  return nullptr;
```
[the remark this answers is not in the document]
Comment (vaithak) [reply lib/Differentiator/BaseForwardModeVisitor.cpp]: Because it's evaluated at compile time, I don't see it performing any side effects we may need to capture in the generated code. Maybe, we will see some use-cases with `consteval` or `contexpr` function calls.

File: lib/Differentiator/ErrorEstimator.cpp [hunk 3]
```diff
@@ -481,8 +481,8 @@ void ErrorEstimationHandler::ActBeforeFinalizingVisitDeclStmt(
   // For all dependent variables, we register them for estimation
   // here.
   for (size_t i = 0; i < decls.size(); i++) {
-    VarDeclDiff VDDiff(static_cast<VarDecl*>(decls[0]),
-                       static_cast<VarDecl*>(declsDiff[0]));
+    DeclDiff<VarDecl> VDDiff(dynamic_cast<VarDecl*>(decls[0]),
```
[the remark this answers is not in the document]
Comment (vgvassilev) [reply lib/Differentiator/ErrorEstimator.cpp:484]: We should just use `cast` here.

File: test/Gradient/FunctionCalls.C [hunk 4]
```diff
@@ -6,6 +6,7 @@
 // CHECK-NOT: {{.*error|warning|note:.*}}
 
 #include "clad/Differentiator/Differentiator.h"
+#include <random>
```
Comment (vgvassilev) [inline test/Gradient/FunctionCalls.C:9]: Do we use anything from `<random>` in this test?

Comment (vaithak) [reply test/Gradient/FunctionCalls.C]: my bad, removed it 👍🏼

**Review by vgvassilev — APPROVED** [review]
LGTM!

**Comment by vgvassilev** [comment]
Can you rebase, the codecov should be fixed by #863

**Comment by vgvassilev** [comment]
Can you add tests to appease codecov?

**Comment by vaithak** [comment]
> Can you add tests to appease codecov?

For the locations related to StaticAssertDecl, it is future proofing for the case we start adding some declarations for static asserts in the generated code. Adding a test for them won't be possible now, as we return `nullptrs` for static asserts.

For the remaining case relation If condition with a declaration, turns out it has some bug, I opened an issue for that here: https://github.com/vgvassilev/clad/issues/865.
