### PR TITLE
Fix #1682

### LINKED ISSUE #1682: Warnings about NULL and module operator
I get these warning from clad:
```
test.orig.cpp:18126:76: warning: statement kind 'GNUNullExpr' is not supported
 18126 |     if ((updateConsValsRhoPIndependent(gasModel, blockFamilyMD, stateLeft, NULL, omegaRSqr, invGammaM1, gamma) == EXIT_FAILURE)) {
       |                                                                            ^~~~
/usr/bin/../lib/clang/20/include/__stddef_null.h:21:14: note: expanded from macro 'NULL'
   21 | #define NULL __null
      |              ^~~~~~
test.orig.cpp:18131:138: warning: attempted to differentiate unsupported operator; treated as non-differentiable
 18131 |             {    *(&j) = ((((((block)->mesh.layout.isStructured)))) ? (Funsigned) (((indexNodeLeft) - ((block->mesh.layout).initialPad)) % ((block->mesh.layout).strideLNode) / ((block->mesh.layout).strideJNode)) : (Funsigned) (1)); *(&k) = ((((((block)->mesh.layout.isStructured)))) ? (Funsigned) (((indexNodeLeft) - ((block->mesh.layout).initialPad)) % ((block->mesh.layout).strideJNode)) : (Funsigned) ((indexNodeLeft))); *(&l) = ((((((block)->mesh.layout.isStructured)))) ? (Funsigned) (((indexNodeLeft) - ((block->mesh.layout).initialPad)) / ((block->mesh.layout).strideLNode)) : (Funsigned) (1)); };
       |                                                                                                                                          ^   
test.orig.cpp:18131:353: warning: attempted to differentiate unsupported operator; treated as non-differentiable
 18131 |             {    *(&j) = ((((((block)->mesh.layout.isStructured)))) ? (Funsigned) (((indexNodeLeft) - ((block->mesh.layout).initialPad)) % ((block->mesh.layout).strideLNode) / ((block->mesh.layout).strideJNode)) : (Funsigned) (1)); *(&k) = ((((((block)->mesh.layout.isStructured)))) ? (Funsigned) (((indexNodeLeft) - ((block->mesh.layout).initialPad)) % ((block->mesh.layout).strideJNode)) : (Funsigned) ((indexNodeLeft))); *(&l) = ((((((block)->mesh.layout.isStructured)))) ? (Funsigned) (((indexNodeLeft) - ((block->mesh.layout).initialPad)) / ((block->mesh.layout).strideLNode)) : (Funsigned) (1)); };
       |                                                                                                                                                                                                                                                                                                                                                                 ^
test.orig.cpp:18132:51: warning: statement kind 'PredefinedExpr' is not supported
 18132 |             print_cell_data(block, indexNodeLeft, __func__, "left state");
       |                                                   ^~~~~~~~
test.orig.cpp:18133:121: warning: statement kind 'PredefinedExpr' is not supported
 18133 |             passSeriousError("/home/msagebaum/Kaiserslautern/mtu/Programms/trace_suite/trace/SOLVER/firstOrderSpace.c", __func__, 129, "ZONE %d at [%d %d %d] !!!\n", (block->zoneId), j, k, l); 

```

The NULL warning is probably hard to handle. What is you current point in that regard? From my view: If the primal code is null safe the derivative code should also be null safe. So NULL for the adjoint variable should not be a problem?

The warning about the modulo operator is kind of a false positive. The operation is just an index computation and does not enter the derivative computation. 

I looked for `PredefinedExpr` but it is not defined in my code. Is this something you add during the differentiation process?

There is still this fault, that I will try to get a reproducer tomorrow.
```
0.  Program arguments: /bin/clang++ -fno-crash-diagnostics -fplugin=/home/msagebaum/Applications/clad/inst/lib64/clad.so -I/home/msagebaum/Applications/clad/inst/include -Xclang -plugin-arg-clad -Xclang -fgenerate-source-file -DCLAD_NO_NUM_DIFF -I/home/msagebaum/Kaiserslautern/mtu/Programms/trace_suite/trace/INCLUDE -I/home/msagebaum/Kaiserslautern/mtu/Programms/trace_suite/build_jacobian_linear_dbg/trace -I/home/msagebaum/Applications/build/include -I/usr/include/openmpi-x86_64/ -I/home/msagebaum/Kaiserslautern/mtu/Programms/trace_suite/trace/AD -I/home/msagebaum/Kaiserslautern/mtu/Programms/trace_suite/contrib/ad_dependencies/adToolbox/include test.orig.cpp -c -o test.o -DNDEBUG -DSIMD_STRUCTS
1.  <eof> parser at end of file
 #0 0x00007f8d9562917a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib64/libLLVM.so.20.1+0x22917a)
 #1 0x00007f8d95626104 llvm::sys::RunSignalHandlers() (/lib64/libLLVM.so.20.1+0x226104)
 #2 0x00007f8d9553f8f4 (/lib64/libLLVM.so.20.1+0x13f8f4)
 #3 0x00007f8d94e28070 __restore_rt (/lib64/libc.so.6+0x1a070)
 #4 0x00007f8d94e81e9c __pthread_kill_implementation (/lib64/libc.so.6+0x73e9c)
 #5 0x00007f8d94e27f3e gsignal (/lib64/libc.so.6+0x19f3e)
 #6 0x00007f8d94e0f6d0 abort (/lib64/libc.so.6+0x16d0)
 #7 0x00007f8d94e0f639 __assert_perror_fail (/lib64/libc.so.6+0x1639)
 #8 0x00007f8d942baae1 clang::FunctionDecl::getParamDecl(unsigned int) const /usr/include/clang/AST/Decl.h:0:5
 #9 0x00007f8d94518f14 clad::ReverseModeVisitor::VisitCallExpr(clang::CallExpr const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeVisitor.cpp:1977:29
#10 0x00007f8d94500b18 clang::StmtVisitorBase<llvm::make_const_ptr, clad::ReverseModeVisitor, clad::StmtDiff>::Visit(clang::Stmt const*) /usr/include/clang/AST/StmtNodes.inc:614:1
#11 0x00007f8d944ff31e clad::ReverseModeVisitor::Visit(clang::Stmt const*, clang::Expr*) /home/msagebaum/Applications/clad/include/clad/Differentiator/ReverseModeVisitor.h:129:11
#12 0x00007f8d944fe69d clad::ReverseModeForwPassVisitor::ProcessSingleStmt(clang::Stmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeForwPassVisitor.cpp:192:17
#13 0x00007f8d944fe761 clad::ReverseModeForwPassVisitor::VisitCompoundStmt(clang::CompoundStmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeForwPassVisitor.cpp:201:29
#14 0x00007f8d94501898 clang::StmtVisitorBase<llvm::make_const_ptr, clad::ReverseModeVisitor, clad::StmtDiff>::Visit(clang::Stmt const*) /usr/include/clang/AST/StmtNodes.inc:1634:1
#15 0x00007f8d944ff31e clad::ReverseModeVisitor::Visit(clang::Stmt const*, clang::Expr*) /home/msagebaum/Applications/clad/include/clad/Differentiator/ReverseModeVisitor.h:129:11
#16 0x00007f8d9450fbb6 clad::ReverseModeVisitor::VisitIfStmt(clang::IfStmt const*)::$_0::operator()(clang::Stmt const*) const /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeVisitor.cpp:856:9
#17 0x00007f8d9450f471 clad::ReverseModeVisitor::VisitIfStmt(clang::IfStmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeVisitor.cpp:875:37
#18 0x00007f8d945017e7 clang::StmtVisitorBase<llvm::make_const_ptr, clad::ReverseModeVisitor, clad::StmtDiff>::Visit(clang::Stmt const*) /usr/include/clang/AST/StmtNodes.inc:1586:1
#19 0x00007f8d944ff31e clad::ReverseModeVisitor::Visit(clang::Stmt const*, clang::Expr*) /home/msagebaum/Applications/clad/include/clad/Differentiator/ReverseModeVisitor.h:129:11
#20 0x00007f8d944fe69d clad::ReverseModeForwPassVisitor::ProcessSingleStmt(clang::Stmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeForwPassVisitor.cpp:192:17
#21 0x00007f8d944fe761 clad::ReverseModeForwPassVisitor::VisitCompoundStmt(clang::CompoundStmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeForwPassVisitor.cpp:201:29
#22 0x00007f8d94501898 clang::StmtVisitorBase<llvm::make_const_ptr, clad::ReverseModeVisitor, clad::StmtDiff>::Visit(clang::Stmt const*) /usr/include/clang/AST/StmtNodes.inc:1634:1
#23 0x00007f8d944ff31e clad::ReverseModeVisitor::Visit(clang::Stmt const*, clang::Expr*) /home/msagebaum/Applications/clad/include/clad/Differentiator/ReverseModeVisitor.h:129:11
#24 0x00007f8d9450fbb6 clad::ReverseModeVisitor::VisitIfStmt(clang::IfStmt const*)::$_0::operator()(clang::Stmt const*) const /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeVisitor.cpp:856:9
#25 0x00007f8d9450f471 clad::ReverseModeVisitor::VisitIfStmt(clang::IfStmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeVisitor.cpp:875:37
#26 0x00007f8d945017e7 clang::StmtVisitorBase<llvm::make_const_ptr, clad::ReverseModeVisitor, clad::StmtDiff>::Visit(clang::Stmt const*) /usr/include/clang/AST/StmtNodes.inc:1586:1
#27 0x00007f8d944ff31e clad::ReverseModeVisitor::Visit(clang::Stmt const*, clang::Expr*) /home/msagebaum/Applications/clad/include/clad/Differentiator/ReverseModeVisitor.h:129:11
#28 0x00007f8d944fe69d clad::ReverseModeForwPassVisitor::ProcessSingleStmt(clang::Stmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeForwPassVisitor.cpp:192:17
#29 0x00007f8d944fe761 clad::ReverseModeForwPassVisitor::VisitCompoundStmt(clang::CompoundStmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeForwPassVisitor.cpp:201:29
#30 0x00007f8d94501898 clang::StmtVisitorBase<llvm::make_const_ptr, clad::ReverseModeVisitor, clad::StmtDiff>::Visit(clang::Stmt const*) /usr/include/clang/AST/StmtNodes.inc:1634:1
#31 0x00007f8d944ff31e clad::ReverseModeVisitor::Visit(clang::Stmt const*, clang::Expr*) /home/msagebaum/Applications/clad/include/clad/Differentiator/ReverseModeVisitor.h:129:11
#32 0x00007f8d944fd0ef clad::ReverseModeForwPassVisitor::Derive() /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeForwPassVisitor.cpp:70:25
#33 0x00007f8d9434ab9b clad::DerivativeBuilder::Derive(clad::DiffRequest const&) /home/msagebaum/Applications/clad/lib/Differentiator/DerivativeBuilder.cpp:568:18
#34 0x00007f8d9401da47 clad::plugin::CladPlugin::ProcessDiffRequest(clad::DiffRequest&) /home/msagebaum/Applications/clad/tools/ClangPlugin.cpp:323:52
#35 0x00007f8d9401ef6e clad::plugin::CladPlugin::FinalizeTranslationUnit() /home/msagebaum/Applications/clad/tools/ClangPlugin.cpp:536:11
#36 0x00007f8d9401fd44 clad::plugin::CladPlugin::HandleTranslationUnit(clang::ASTContext&) /home/msagebaum/Applications/clad/tools/ClangPlugin.cpp:577:9
#37 0x00007f8da055e2ec clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) (/lib64/libclang-cpp.so.20.1+0x295e2ec)
#38 0x00007f8d9de12d49 clang::ParseAST(clang::Sema&, bool, bool) (/lib64/libclang-cpp.so.20.1+0x212d49)
#39 0x00007f8da05191af clang::FrontendAction::Execute() (/lib64/libclang-cpp.so.20.1+0x29191af)
#40 0x00007f8da047ba24 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/lib64/libclang-cpp.so.20.1+0x287ba24)
#41 0x00007f8da05accee clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/lib64/libclang-cpp.so.20.1+0x29accee)
#42 0x00005608bd367695 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/bin/clang+++0xa695)
#43 0x00005608bd363727 (/bin/clang+++0x6727)
#44 0x00007f8da001c0ad (/lib64/libclang-cpp.so.20.1+0x241c0ad)
#45 0x00007f8d9553f600 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/lib64/libLLVM.so.20.1+0x13f600)
#46 0x00007f8da001b965 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (/lib64/libclang-cpp.so.20.1+0x241b965)
#47 0x00007f8d9ffd7bf9 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/lib64/libclang-cpp.so.20.1+0x23d7bf9)
#48 0x00007f8d9ffd7eb7 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/lib64/libclang-cpp.so.20.1+0x23d7eb7)
#49 0x00007f8d9fffaa09 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/lib64/libclang-cpp.so.20.1+0x23faa09)
#50 0x00005608bd362b54 clang_main(int, char**, llvm::ToolContext const&) (/bin/clang+++0x5b54)
#51 0x00005608bd3729a8 main (/bin/clang+++0x159a8)
#52 0x00007f8d94e11575 __libc_start_call_main (/lib64/libc.so.6+0x3575)
#53 0x00007f8d94e11628 __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x3628)
#54 0x00005608bd360e05 _start (/bin/clang+++0x3e05)

```

### LINKED ISSUE #1683: Fault in generating files.
I tried to create a reproducer for the assert mentioned in #1682 . I do not know if the reduce makes sense. Maybe you can have a look and tell me if I need to constrain this further. 

Reproducer:
```
#include "clad/Differentiator/Differentiator.h"
void a(...);
int b;
void c(float) { a(b); }
float d;
void e() {
  c(d);
  clad::gradient(e);
}
```

Error:
```
test.cpp:8:3: error: attempted to differentiate function with no parameters
    8 |   clad::gradient(e);
      |   ^~~~
test.cpp:3:5: warning: gradient uses a global variable 'b'; rerunning the gradient requires 'b' to be reset
    3 | int b;
      |     ^
clang++: /usr/include/clang/AST/Decl.h:2680: const ParmVarDecl *clang::FunctionDecl::getParamDecl(unsigned int) const: Assertion `i < getNumParams() && "Illegal param #"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /bin/clang++ -fno-crash-diagnostics -fplugin=/home/msagebaum/Applications/clad/inst/lib64/clad.so -I/home/msagebaum/Applications/clad/inst/include -Xclang -plugin-arg-clad -Xclang -fgenerate-source-file -DCLAD_NO_NUM_DIFF -I/home/msagebaum/Kaiserslautern/mtu/Programms/trace_suite/trace/INCLUDE -I/home/msagebaum/Kaiserslautern/mtu/Programms/trace_suite/build_jacobian_linear_dbg/trace -I/home/msagebaum/Applications/build/include -I/usr/include/openmpi-x86_64/ -I/home/msagebaum/Kaiserslautern/mtu/Programms/trace_suite/trace/AD -I/home/msagebaum/Kaiserslautern/mtu/Programms/trace_suite/contrib/ad_dependencies/adToolbox/include test.cpp -c -o test.o -DNDEBUG -DSIMD_STRUCTS
1.	<eof> parser at end of file
2.	Building code for '<void c(float)>[name=c, order=1, mode=pullback, args='', tbr]'
While visiting <CallExpr> [ 'test.cpp:4:17', 'test.cpp:4:20']

--- Begin Stmt Dump ---
a(b)
--- End Stmt Dump ---
 #0 0x00007faf34a2917a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib64/libLLVM.so.20.1+0x22917a)
 #1 0x00007faf34a26104 llvm::sys::RunSignalHandlers() (/lib64/libLLVM.so.20.1+0x226104)
 #2 0x00007faf3493f8f4 (/lib64/libLLVM.so.20.1+0x13f8f4)
 #3 0x00007faf34228070 __restore_rt (/lib64/libc.so.6+0x1a070)
 #4 0x00007faf34281e9c __pthread_kill_implementation (/lib64/libc.so.6+0x73e9c)
 #5 0x00007faf34227f3e gsignal (/lib64/libc.so.6+0x19f3e)
 #6 0x00007faf3420f6d0 abort (/lib64/libc.so.6+0x16d0)
 #7 0x00007faf3420f639 __assert_perror_fail (/lib64/libc.so.6+0x1639)
 #8 0x00007faf334baae1 clang::FunctionDecl::getParamDecl(unsigned int) const /usr/include/clang/AST/Decl.h:0:5
 #9 0x00007faf33718f14 clad::ReverseModeVisitor::VisitCallExpr(clang::CallExpr const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeVisitor.cpp:1977:29
#10 0x00007faf33700b18 clang::StmtVisitorBase<llvm::make_const_ptr, clad::ReverseModeVisitor, clad::StmtDiff>::Visit(clang::Stmt const*) /usr/include/clang/AST/StmtNodes.inc:614:1
#11 0x00007faf336ff31e clad::ReverseModeVisitor::Visit(clang::Stmt const*, clang::Expr*) /home/msagebaum/Applications/clad/include/clad/Differentiator/ReverseModeVisitor.h:129:11
#12 0x00007faf3370f085 clad::ReverseModeVisitor::DifferentiateSingleStmt(clang::Stmt const*, clang::Expr*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeVisitor.cpp:3017:22
#13 0x00007faf3370ef6d clad::ReverseModeVisitor::VisitCompoundStmt(clang::CompoundStmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeVisitor.cpp:791:31
#14 0x00007faf33701898 clang::StmtVisitorBase<llvm::make_const_ptr, clad::ReverseModeVisitor, clad::StmtDiff>::Visit(clang::Stmt const*) /usr/include/clang/AST/StmtNodes.inc:1634:1
#15 0x00007faf336ff31e clad::ReverseModeVisitor::Visit(clang::Stmt const*, clang::Expr*) /home/msagebaum/Applications/clad/include/clad/Differentiator/ReverseModeVisitor.h:129:11
#16 0x00007faf3370d5b2 clad::ReverseModeVisitor::DifferentiateWithClad() /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeVisitor.cpp:469:25
#17 0x00007faf3370a836 clad::ReverseModeVisitor::Derive() /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeVisitor.cpp:338:9
#18 0x00007faf3354aadd clad::DerivativeBuilder::Derive(clad::DiffRequest const&) /home/msagebaum/Applications/clad/lib/Differentiator/DerivativeBuilder.cpp:565:18
#19 0x00007faf3321da47 clad::plugin::CladPlugin::ProcessDiffRequest(clad::DiffRequest&) /home/msagebaum/Applications/clad/tools/ClangPlugin.cpp:323:52
#20 0x00007faf3321ef6e clad::plugin::CladPlugin::FinalizeTranslationUnit() /home/msagebaum/Applications/clad/tools/ClangPlugin.cpp:536:11
#21 0x00007faf3321fd44 clad::plugin::CladPlugin::HandleTranslationUnit(clang::ASTContext&) /home/msagebaum/Applications/clad/tools/ClangPlugin.cpp:577:9
#22 0x00007faf3f95e2ec clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) (/lib64/libclang-cpp.so.20.1+0x295e2ec)
#23 0x00007faf3d212d49 clang::ParseAST(clang::Sema&, bool, bool) (/lib64/libclang-cpp.so.20.1+0x212d49)
#24 0x00007faf3f9191af clang::FrontendAction::Execute() (/lib64/libclang-cpp.so.20.1+0x29191af)
#25 0x00007faf3f87ba24 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/lib64/libclang-cpp.so.20.1+0x287ba24)
#26 0x00007faf3f9accee clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/lib64/libclang-cpp.so.20.1+0x29accee)
#27 0x00005635e24bc695 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/bin/clang+++0xa695)
#28 0x00005635e24b8727 (/bin/clang+++0x6727)
#29 0x00007faf3f41c0ad (/lib64/libclang-cpp.so.20.1+0x241c0ad)
#30 0x00007faf3493f600 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/lib64/libLLVM.so.20.1+0x13f600)
#31 0x00007faf3f41b965 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (/lib64/libclang-cpp.so.20.1+0x241b965)
#32 0x00007faf3f3d7bf9 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/lib64/libclang-cpp.so.20.1+0x23d7bf9)
#33 0x00007faf3f3d7eb7 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/lib64/libclang-cpp.so.20.1+0x23d7eb7)
#34 0x00007faf3f3faa09 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/lib64/libclang-cpp.so.20.1+0x23faa09)
#35 0x00005635e24b7b54 clang_main(int, char**, llvm::ToolContext const&) (/bin/clang+++0x5b54)
#36 0x00005635e24c79a8 main (/bin/clang+++0x159a8)
#37 0x00007faf34211575 __libc_start_call_main (/lib64/libc.so.6+0x3575)
#38 0x00007faf34211628 __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x3628)
#39 0x00005635e24b5e05 _start (/bin/clang+++0x3e05)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
```

Command line:
```
/bin/clang++ -fno-crash-diagnostics -fplugin=/home/msagebaum/Applications/clad/inst/lib64/clad.so -I/home/msagebaum/Applications/clad/inst/include -Xclang -plugin-arg-clad -Xclang -fgenerate-source-file -DCLAD_NO_NUM_DIFF test.cpp -c -o test.o
```

The original output is:
```
In file included from test.orig.cpp:144:
/usr/bin/../lib/gcc/x86_64-redhat-linux/15/../../../../include/c++/15/ccomplex:51:4: warning: "<ccomplex> is deprecated in C++17, use <complex> instead" [-W#warnings]
   51 | #  warning "<ccomplex> is deprecated in C++17, use <complex> instead"
      |    ^
test.orig.cpp:21805:49: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
 21805 |         if ((block->md->spaceSetup.riemann.type == SLAU2_SOLVER)) {
       |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
test.orig.cpp:21805:49: note: remove extraneous parentheses around the comparison to silence this warning
 21805 |         if ((block->md->spaceSetup.riemann.type == SLAU2_SOLVER)) {
       |             ~                                   ^              ~
test.orig.cpp:21805:49: note: use '=' to turn this equality comparison into an assignment
 21805 |         if ((block->md->spaceSetup.riemann.type == SLAU2_SOLVER)) {
       |                                                 ^~
       |                                                 =
test.orig.cpp:21809:54: warning: equality comparison with extraneous parentheses [-Wparentheses-equality]
 21809 |         else if ((block->md->spaceSetup.riemann.type == CENTRAL_KINETIC_ENERGY_PRESERVING_SOLVER)) {
       |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test.orig.cpp:21809:54: note: remove extraneous parentheses around the comparison to silence this warning
 21809 |         else if ((block->md->spaceSetup.riemann.type == CENTRAL_KINETIC_ENERGY_PRESERVING_SOLVER)) {
       |                  ~                                   ^                                          ~
test.orig.cpp:21809:54: note: use '=' to turn this equality comparison into an assignment
 21809 |         else if ((block->md->spaceSetup.riemann.type == CENTRAL_KINETIC_ENERGY_PRESERVING_SOLVER)) {
       |                                                      ^~
       |                                                      =
test.orig.cpp:18126:76: warning: statement kind 'GNUNullExpr' is not supported
 18126 |     if ((updateConsValsRhoPIndependent(gasModel, blockFamilyMD, stateLeft, NULL, omegaRSqr, invGammaM1, gamma) == EXIT_FAILURE)) {
       |                                                                            ^~~~
/usr/bin/../lib/clang/20/include/__stddef_null.h:21:14: note: expanded from macro 'NULL'
   21 | #define NULL __null
      |              ^~~~~~
test.orig.cpp:18131:138: warning: attempted to differentiate unsupported operator; treated as non-differentiable
 18131 |             {    *(&j) = ((((((block)->mesh.layout.isStructured)))) ? (Funsigned) (((indexNodeLeft) - ((block->mesh.layout).initialPad)) % ((block->mesh.layout).strideLNode) / ((block->mesh.layout).strideJNode)) : (Funsigned) (1)); *(&k) = ((((((block)->mesh.layout.isStructured)))) ? (Funsigned) (((indexNodeLeft) - ((block->mesh.layout).initialPad)) % ((block->mesh.layout).strideJNode)) : (Funsigned) ((indexNodeLeft))); *(&l) = ((((((block)->mesh.layout.isStructured)))) ? (Funsigned) (((indexNodeLeft) - ((block->mesh.layout).initialPad)) / ((block->mesh.layout).strideLNode)) : (Funsigned) (1)); };
       |                                                                                                                                          ^
test.orig.cpp:18131:353: warning: attempted to differentiate unsupported operator; treated as non-differentiable
 18131 |             {    *(&j) = ((((((block)->mesh.layout.isStructured)))) ? (Funsigned) (((indexNodeLeft) - ((block->mesh.layout).initialPad)) % ((block->mesh.layout).strideLNode) / ((block->mesh.layout).strideJNode)) : (Funsigned) (1)); *(&k) = ((((((block)->mesh.layout.isStructured)))) ? (Funsigned) (((indexNodeLeft) - ((block->mesh.layout).initialPad)) % ((block->mesh.layout).strideJNode)) : (Funsigned) ((indexNodeLeft))); *(&l) = ((((((block)->mesh.layout.isStructured)))) ? (Funsigned) (((indexNodeLeft) - ((block->mesh.layout).initialPad)) / ((block->mesh.layout).strideLNode)) : (Funsigned) (1)); };
       |                                                                                                                                                                                                                                                                                                                                                                 ^
test.orig.cpp:18132:51: warning: statement kind 'PredefinedExpr' is not supported
 18132 |             print_cell_data(block, indexNodeLeft, __func__, "left state");
       |                                                   ^~~~~~~~
test.orig.cpp:18133:121: warning: statement kind 'PredefinedExpr' is not supported
 18133 |             passSeriousError("/home/msagebaum/Kaiserslautern/mtu/Programms/trace_suite/trace/SOLVER/firstOrderSpace.c", __func__, 129, "ZONE %d at [%d %d %d] !!!\n", (block->zoneId), j, k, l);
       |                                                                                                                         ^~~~~~~~
clang++: /usr/include/clang/AST/Decl.h:2680: const ParmVarDecl *clang::FunctionDecl::getParamDecl(unsigned int) const: Assertion `i < getNumParams() && "Illegal param #"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /bin/clang++ -fno-crash-diagnostics -fplugin=/home/msagebaum/Applications/clad/inst/lib64/clad.so -I/home/msagebaum/Applications/clad/inst/include -Xclang -plugin-arg-clad -Xclang -fgenerate-source-file -DCLAD_NO_NUM_DIFF -I/home/msagebaum/Kaiserslautern/mtu/Programms/trace_suite/trace/INCLUDE -I/home/msagebaum/Kaiserslautern/mtu/Programms/trace_suite/build_jacobian_linear_dbg/trace -I/home/msagebaum/Applications/build/include -I/usr/include/openmpi-x86_64/ -I/home/msagebaum/Kaiserslautern/mtu/Programms/trace_suite/trace/AD -I/home/msagebaum/Kaiserslautern/mtu/Programms/trace_suite/contrib/ad_dependencies/adToolbox/include test.orig.cpp -c -o test.o -DNDEBUG -DSIMD_STRUCTS
1.	<eof> parser at end of file
 #0 0x00007fa8b7a2917a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib64/libLLVM.so.20.1+0x22917a)
 #1 0x00007fa8b7a26104 llvm::sys::RunSignalHandlers() (/lib64/libLLVM.so.20.1+0x226104)
 #2 0x00007fa8b793f8f4 (/lib64/libLLVM.so.20.1+0x13f8f4)
 #3 0x00007fa8b7228070 __restore_rt (/lib64/libc.so.6+0x1a070)
 #4 0x00007fa8b7281e9c __pthread_kill_implementation (/lib64/libc.so.6+0x73e9c)
 #5 0x00007fa8b7227f3e gsignal (/lib64/libc.so.6+0x19f3e)
 #6 0x00007fa8b720f6d0 abort (/lib64/libc.so.6+0x16d0)
 #7 0x00007fa8b720f639 __assert_perror_fail (/lib64/libc.so.6+0x1639)
 #8 0x00007fa8b66baae1 clang::FunctionDecl::getParamDecl(unsigned int) const /usr/include/clang/AST/Decl.h:0:5
 #9 0x00007fa8b6918f14 clad::ReverseModeVisitor::VisitCallExpr(clang::CallExpr const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeVisitor.cpp:1977:29
#10 0x00007fa8b6900b18 clang::StmtVisitorBase<llvm::make_const_ptr, clad::ReverseModeVisitor, clad::StmtDiff>::Visit(clang::Stmt const*) /usr/include/clang/AST/StmtNodes.inc:614:1
#11 0x00007fa8b68ff31e clad::ReverseModeVisitor::Visit(clang::Stmt const*, clang::Expr*) /home/msagebaum/Applications/clad/include/clad/Differentiator/ReverseModeVisitor.h:129:11
#12 0x00007fa8b68fe69d clad::ReverseModeForwPassVisitor::ProcessSingleStmt(clang::Stmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeForwPassVisitor.cpp:192:17
#13 0x00007fa8b68fe761 clad::ReverseModeForwPassVisitor::VisitCompoundStmt(clang::CompoundStmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeForwPassVisitor.cpp:201:29
#14 0x00007fa8b6901898 clang::StmtVisitorBase<llvm::make_const_ptr, clad::ReverseModeVisitor, clad::StmtDiff>::Visit(clang::Stmt const*) /usr/include/clang/AST/StmtNodes.inc:1634:1
#15 0x00007fa8b68ff31e clad::ReverseModeVisitor::Visit(clang::Stmt const*, clang::Expr*) /home/msagebaum/Applications/clad/include/clad/Differentiator/ReverseModeVisitor.h:129:11
#16 0x00007fa8b690fbb6 clad::ReverseModeVisitor::VisitIfStmt(clang::IfStmt const*)::$_0::operator()(clang::Stmt const*) const /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeVisitor.cpp:856:9
#17 0x00007fa8b690f471 clad::ReverseModeVisitor::VisitIfStmt(clang::IfStmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeVisitor.cpp:875:37
#18 0x00007fa8b69017e7 clang::StmtVisitorBase<llvm::make_const_ptr, clad::ReverseModeVisitor, clad::StmtDiff>::Visit(clang::Stmt const*) /usr/include/clang/AST/StmtNodes.inc:1586:1
#19 0x00007fa8b68ff31e clad::ReverseModeVisitor::Visit(clang::Stmt const*, clang::Expr*) /home/msagebaum/Applications/clad/include/clad/Differentiator/ReverseModeVisitor.h:129:11
#20 0x00007fa8b68fe69d clad::ReverseModeForwPassVisitor::ProcessSingleStmt(clang::Stmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeForwPassVisitor.cpp:192:17
#21 0x00007fa8b68fe761 clad::ReverseModeForwPassVisitor::VisitCompoundStmt(clang::CompoundStmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeForwPassVisitor.cpp:201:29
#22 0x00007fa8b6901898 clang::StmtVisitorBase<llvm::make_const_ptr, clad::ReverseModeVisitor, clad::StmtDiff>::Visit(clang::Stmt const*) /usr/include/clang/AST/StmtNodes.inc:1634:1
#23 0x00007fa8b68ff31e clad::ReverseModeVisitor::Visit(clang::Stmt const*, clang::Expr*) /home/msagebaum/Applications/clad/include/clad/Differentiator/ReverseModeVisitor.h:129:11
#24 0x00007fa8b690fbb6 clad::ReverseModeVisitor::VisitIfStmt(clang::IfStmt const*)::$_0::operator()(clang::Stmt const*) const /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeVisitor.cpp:856:9
#25 0x00007fa8b690f471 clad::ReverseModeVisitor::VisitIfStmt(clang::IfStmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeVisitor.cpp:875:37
#26 0x00007fa8b69017e7 clang::StmtVisitorBase<llvm::make_const_ptr, clad::ReverseModeVisitor, clad::StmtDiff>::Visit(clang::Stmt const*) /usr/include/clang/AST/StmtNodes.inc:1586:1
#27 0x00007fa8b68ff31e clad::ReverseModeVisitor::Visit(clang::Stmt const*, clang::Expr*) /home/msagebaum/Applications/clad/include/clad/Differentiator/ReverseModeVisitor.h:129:11
#28 0x00007fa8b68fe69d clad::ReverseModeForwPassVisitor::ProcessSingleStmt(clang::Stmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeForwPassVisitor.cpp:192:17
#29 0x00007fa8b68fe761 clad::ReverseModeForwPassVisitor::VisitCompoundStmt(clang::CompoundStmt const*) /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeForwPassVisitor.cpp:201:29
#30 0x00007fa8b6901898 clang::StmtVisitorBase<llvm::make_const_ptr, clad::ReverseModeVisitor, clad::StmtDiff>::Visit(clang::Stmt const*) /usr/include/clang/AST/StmtNodes.inc:1634:1
#31 0x00007fa8b68ff31e clad::ReverseModeVisitor::Visit(clang::Stmt const*, clang::Expr*) /home/msagebaum/Applications/clad/include/clad/Differentiator/ReverseModeVisitor.h:129:11
#32 0x00007fa8b68fd0ef clad::ReverseModeForwPassVisitor::Derive() /home/msagebaum/Applications/clad/lib/Differentiator/ReverseModeForwPassVisitor.cpp:70:25
#33 0x00007fa8b674ab9b clad::DerivativeBuilder::Derive(clad::DiffRequest const&) /home/msagebaum/Applications/clad/lib/Differentiator/DerivativeBuilder.cpp:568:18
#34 0x00007fa8b641da47 clad::plugin::CladPlugin::ProcessDiffRequest(clad::DiffRequest&) /home/msagebaum/Applications/clad/tools/ClangPlugin.cpp:323:52
#35 0x00007fa8b641ef6e clad::plugin::CladPlugin::FinalizeTranslationUnit() /home/msagebaum/Applications/clad/tools/ClangPlugin.cpp:536:11
#36 0x00007fa8b641fd44 clad::plugin::CladPlugin::HandleTranslationUnit(clang::ASTContext&) /home/msagebaum/Applications/clad/tools/ClangPlugin.cpp:577:9
#37 0x00007fa8c295e2ec clang::MultiplexConsumer::HandleTranslationUnit(clang::ASTContext&) (/lib64/libclang-cpp.so.20.1+0x295e2ec)
#38 0x00007fa8c0212d49 clang::ParseAST(clang::Sema&, bool, bool) (/lib64/libclang-cpp.so.20.1+0x212d49)
#39 0x00007fa8c29191af clang::FrontendAction::Execute() (/lib64/libclang-cpp.so.20.1+0x29191af)
#40 0x00007fa8c287ba24 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/lib64/libclang-cpp.so.20.1+0x287ba24)
#41 0x00007fa8c29accee clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/lib64/libclang-cpp.so.20.1+0x29accee)
#42 0x0000562b9b4a3695 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/bin/clang+++0xa695)
#43 0x0000562b9b49f727 (/bin/clang+++0x6727)
#44 0x00007fa8c241c0ad (/lib64/libclang-cpp.so.20.1+0x241c0ad)
#45 0x00007fa8b793f600 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/lib64/libLLVM.so.20.1+0x13f600)
#46 0x00007fa8c241b965 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (/lib64/libclang-cpp.so.20.1+0x241b965)
#47 0x00007fa8c23d7bf9 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/lib64/libclang-cpp.so.20.1+0x23d7bf9)
#48 0x00007fa8c23d7eb7 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/lib64/libclang-cpp.so.20.1+0x23d7eb7)
#49 0x00007fa8c23faa09 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/lib64/libclang-cpp.so.20.1+0x23faa09)
#50 0x0000562b9b49eb54 clang_main(int, char**, llvm::ToolContext const&) (/bin/clang+++0x5b54)
#51 0x0000562b9b4ae9a8 main (/bin/clang+++0x159a8)
#52 0x00007fa8b7211575 __libc_start_call_main (/lib64/libc.so.6+0x3575)
#53 0x00007fa8b7211628 __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x3628)
#54 0x0000562b9b49ce05 _start (/bin/clang+++0x3e05)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)

```

### PR DESCRIPTION
**Pull request by Fermats-Last-Theorem**
This PR fixes the issues that popped up in #1682 for Variadic functions, modulo operators and adds regression test.
Fixes #1682. Fixes #1683

### CODE REVIEW

File: include/clad/Differentiator/ReverseModeVisitor.h [hunk 1]
```diff
@@ -407,6 +407,8 @@ namespace clad {
     StmtDiff VisitForStmt(const clang::ForStmt* FS);
     StmtDiff VisitIfStmt(const clang::IfStmt* If);
     StmtDiff VisitImplicitCastExpr(const clang::ImplicitCastExpr* ICE);
+    StmtDiff VisitGNUNullExpr(const clang::GNUNullExpr *E);
```
Comment (vgvassilev) [inline include/clad/Differentiator/ReverseModeVisitor.h]: We should also have these in the other visitors. Perhaps that should be in the base class if possible..

Comment (Fermats-Last-Theorem) [reply include/clad/Differentiator/ReverseModeVisitor.h]: I could add something like HandleXXX in VisitorBase and then call that inside VisitXXX in all the visitors. Does that work?

Comment (vgvassilev) [reply include/clad/Differentiator/ReverseModeVisitor.h]: Ok, that seems too much of a refactoring. Let's keep it like this but please duplicate the logic in `BaseForwardModeVisitor.h`.

Comment (Fermats-Last-Theorem) [reply include/clad/Differentiator/ReverseModeVisitor.h]: Done.
