### PR TITLE
Fixed nested hessian context loss and reverse mode memory OOB error for nested arrays

### LINKED ISSUE #1737: `clad::hessian` fails for nested functions
Example as a ROOT macro, including extensive validation:
```c++
#include <Math/CladDerivator.h>

#define DO_HESSIAN

double func_3(double *params)
{
   return params[0] * params[0] + params[1] * params[1] + params[0] * params[1];
}

double func_2(double *params)
{
   return func_3(params) - std::log(params[0]);
}

#pragma clad ON
void gradient_request()
{
   clad::gradient(func_2, "params");
#ifdef DO_HESSIAN
   clad::hessian(func_2, "params[0:2]");
#endif
}
#pragma clad OFF

std::vector<double> parametersVec = {0.5, -1, 2};

// To run as a ROOT macro
void ConstraintSum()
{
   const std::size_t n = parametersVec.size();

   std::vector<double> gradientVec(n);

   auto func = [&](std::span<double> params) { return func_2(params.data()); };
   auto grad = [&](std::span<double> params, std::span<double> out) {
      return func_2_grad(parametersVec.data(), out.data());
   };

   grad(parametersVec, gradientVec);

   auto numDiff = [&](int i) {
      const double eps = 1e-6;
      std::vector<double> p{parametersVec};
      p[i] = parametersVec[i] - eps;
      double funcValDown = func(p);
      p[i] = parametersVec[i] + eps;
      double funcValUp = func(p);
      return (funcValUp - funcValDown) / (2 * eps);
   };

   for (std::size_t i = 0; i < parametersVec.size(); ++i) {
      std::cout << i << ":" << std::endl;
      std::cout << "  numr : " << numDiff(i) << std::endl;
      std::cout << "  clad : " << gradientVec[i] << std::endl;
   }

#ifdef DO_HESSIAN
   std::cout << "\n";

   auto hess = [&](std::span<double> params, std::span<double> out) {
      return func_2_hessian(params.data(), out.data());
   };

   std::vector<double> hessianVec(n * n);
   hess(parametersVec, hessianVec);

   // ---------- Numerical Hessian ----------
   // Uses central differences:
   // diag: (f(x+ei)-2f(x)+f(x-ei))/eps^2
   // offdiag: (f(++ ) - f(+-) - f(-+) + f(--)) / (4 eps^2)
   auto numHess = [&](std::size_t i, std::size_t j) {
      const double eps = 1e-5; // often needs to be a bit larger than grad eps
      std::vector<double> p(parametersVec.begin(), parametersVec.end());

      if (i == j) {
         const double f0 = func(p);

         p[i] = parametersVec[i] + eps;
         const double fUp = func(p);

         p[i] = parametersVec[i] - eps;
         const double fDown = func(p);

         return (fUp - 2.0 * f0 + fDown) / (eps * eps);
      } else {
         // f(x_i + eps, x_j + eps)
         p[i] = parametersVec[i] + eps;
         p[j] = parametersVec[j] + eps;
         const double fPP = func(p);

         // f(x_i + eps, x_j - eps)
         p[i] = parametersVec[i] + eps;
         p[j] = parametersVec[j] - eps;
         const double fPM = func(p);

         // f(x_i - eps, x_j + eps)
         p[i] = parametersVec[i] - eps;
         p[j] = parametersVec[j] + eps;
         const double fMP = func(p);

         // f(x_i - eps, x_j - eps)
         p[i] = parametersVec[i] - eps;
         p[j] = parametersVec[j] - eps;
         const double fMM = func(p);

         return (fPP - fPM - fMP + fMM) / (4.0 * eps * eps);
      }
   };

   // Compute full numerical Hessian
   std::vector<double> numHessianVec(n * n);
   for (std::size_t i = 0; i < n; ++i) {
      for (std::size_t j = 0; j < n; ++j) {
         numHessianVec[i + n * j] = numHess(i, j); // keep same layout as your print
      }
   }

   // ---------- Compare & print ----------
   std::cout << "Hessian comparison (clad vs numeric vs diff):\n\n";

   for (std::size_t i = 0; i < n; ++i) {
      for (std::size_t j = 0; j < n; ++j) {
         const std::size_t idx = i + n * j; // same indexing you used
         const double cladH = hessianVec[idx];
         const double numH = numHessianVec[idx];
         const double diff = cladH - numH;

         std::cout << "[" << i << "," << j << "] "
                   << "clad=" << cladH << "  num=" << numH << "  diff=" << diff << "\n";
      }
   }

   std::cout << "\nRaw Clad Hessian matrix:\n";
   for (std::size_t i = 0; i < n; ++i) {
      for (std::size_t j = 0; j < n; ++j) {
         std::cout << hessianVec[i + n * j] << "   ";
      }
      std::cout << "\n";
   }

   std::cout << "\nRaw Numerical Hessian matrix:\n";
   for (std::size_t i = 0; i < n; ++i) {
      for (std::size_t j = 0; j < n; ++j) {
         std::cout << numHessianVec[i + n * j] << "   ";
      }
      std::cout << "\n";
   }
#endif
}
```
The output is wrong:
```txt
Processing ConstraintSum.C...
0:
  numr : -2
  clad : -2
1:
  numr : -1.5
  clad : -1.5
2:
  numr : 0
  clad : 0

Hessian comparison (clad vs numeric vs diff):

[0,0] clad=4  num=6  diff=-2
[0,1] clad=0  num=1  diff=-1
[0,2] clad=0  num=0  diff=0
[1,0] clad=0  num=1  diff=-1
[1,1] clad=0  num=2  diff=-2
[1,2] clad=0  num=0  diff=0
[2,0] clad=0  num=0  diff=0
[2,1] clad=0  num=0  diff=0
[2,2] clad=0  num=0  diff=0

Raw Clad Hessian matrix:
4   0   0
0   0   0
0   0   0

Raw Numerical Hessian matrix:
6   1   0
1   2   0
0   0   0
```
This should work, because it's a basic requirement to implement combined likelihood fits.

### PR DESCRIPTION
**Pull request by Fermats-Last-Theorem**
This PR resolves the issue where Clad loses the original array dimension during Hessian calculation for nested function calls, which leads to incorrect derivatives as shown in Issue #1737 and causes OOB memory access in the reverse pass . It fixes #1737. 

When `diffplanner` computes `clad::hessian(f, "p[0:4]")`, it generates sub requests for each index. This causes the original array capacity to be lost. The forward pass then uses this wrong capacity to generate an array for this size. The reverse mode then writes cross term adjoints till the original capacity causing OOB errors.

This PR tracks total size through sub requests and generate temporary arrays of correct size. This resolves the OOB errors in the reverse pass. 

Added tests for NestedArrays.

### CODE REVIEW

File: lib/Differentiator/BaseForwardModeVisitor.cpp [hunk 1]
```diff
@@ -1117,9 +1119,89 @@ StmtDiff BaseForwardModeVisitor::VisitCallExpr(const CallExpr* CE) {
...
+              llvm::APInt sizeAPI(
+                  m_Context.getTypeSize(m_Context.getSizeType()), arrSize);
+#if CLANG_VERSION_MAJOR >= 18
+              QualType arrType = m_Context.getConstantArrayType(
+                  elemType, sizeAPI, nullptr, clang::ArraySizeModifier::Normal,
+                  0);
+#else
+              QualType arrType = m_Context.getConstantArrayType(
+                  elemType, sizeAPI, nullptr, clang::ArrayType::Normal, 0);
+#endif
```
Comment (vgvassilev) [inline lib/Differentiator/BaseForwardModeVisitor.cpp]: We should use `clad_compat::getConstantArrayType` here.

File: lib/Differentiator/BaseForwardModeVisitor.cpp [hunk 2]
```diff
@@ -1117,9 +1119,89 @@ StmtDiff BaseForwardModeVisitor::VisitCallExpr(const CallExpr* CE) {
...
+
+              llvm::SmallVector<Expr*, 4> initExprs;
+              for (std::size_t k = 0; k < arrSize; ++k) {
+                Expr* idxExpr = ConstantFolder::synthesizeLiteral(
+                    m_Context.IntTy, m_Context, k);
+
+                Expr* subExpr = new (m_Context) ArraySubscriptExpr( // NOLINT
```
Comment (vgvassilev) [inline lib/Differentiator/BaseForwardModeVisitor.cpp]: The NOLINT(should-have-the-exact-check).

File: lib/Differentiator/BaseForwardModeVisitor.cpp [hunk 3]
```diff
@@ -1117,9 +1119,89 @@ StmtDiff BaseForwardModeVisitor::VisitCallExpr(const CallExpr* CE) {
...
+
+      if ((!dArg || clad::utils::IsZeroOrNullValue(dArg)) &&
+          (arg->getType()->isPointerType() || arg->getType()->isArrayType())) {
+        const Expr* cleanArg = arg->IgnoreParenImpCasts();
+        if (const auto* DRE = dyn_cast<DeclRefExpr>(cleanArg)) {
+          if (const auto* VD = dyn_cast<VarDecl>(DRE->getDecl())) {
+
+            std::size_t arrSize = 0;
+
+            /// try to get the size from the AST
```
Comment (vgvassilev) [inline lib/Differentiator/BaseForwardModeVisitor.cpp]: We don't need doxygen-style comments but we need full sentences.

File: lib/Differentiator/BaseForwardModeVisitor.cpp [hunk 4]
```diff
@@ -1117,9 +1119,89 @@ StmtDiff BaseForwardModeVisitor::VisitCallExpr(const CallExpr* CE) {
...
+                  initExprs.push_back(subDx);
+              }
+
+              auto* initList = new (m_Context) InitListExpr( // NOLINT
+                  m_Context, CE->getBeginLoc(), initExprs, CE->getEndLoc());
+              initList->setType(arrType);
+
+              TypeSourceInfo* tInfo =
+                  m_Context.getTrivialTypeSourceInfo(arrType);
+              auto* CLE = new (m_Context) CompoundLiteralExpr( // NOLINT
```
Comment (vgvassilev) [inline lib/Differentiator/BaseForwardModeVisitor.cpp]:
```suggestion
              // NOLINTNEXTLINE(...)
              auto* CLE = new (m_Context) CompoundLiteralExpr(
```

File: include/clad/Differentiator/ParseDiffArgsTypes.h [hunk 5]
```diff
@@ -69,6 +69,8 @@ namespace clad {
     const clang::ValueDecl* param = nullptr;
     /// array index range associated with the parameter.
     IndexInterval paramIndexInterval;
+    /// track the true global capacity across sub-requests
+    std::size_t TotalCapacity = 0;
```
Comment (vgvassilev) [inline include/clad/Differentiator/ParseDiffArgsTypes.h:73]: Do we need this state here?

Comment (Fermats-Last-Theorem) [reply include/clad/Differentiator/ParseDiffArgsTypes.h:73]: In `DiffCollector::VisitCallExpr` we overwrite the `paramIndexInterval` for hessians which results in loss of the original size of the array which is why we need a state to retain it. The Fixme also notes this might lead to issues.
``` cpp
if (utils::isArrayOrPointerType(PVD->getType())) {
            // FIXME: We shouldn't synthesize Args strings.
            for (auto i = indexInterval.Start; i < indexInterval.Finish; ++i) {
              auto independentArgString =
                  PVD->getNameAsString() + "[" + std::to_string(i) + "]";
              forwRequest.Args = utils::CreateStringLiteral(
                  m_Sema.getASTContext(), independentArgString);
              forwRequest.UpdateDiffParamsInfo(m_Sema);
              if (!forwRequest.DVI.empty())
                forwRequest.DVI.back().TotalCapacity = indexInterval.Finish;
              LookupCustomDerivativeDecl(forwRequest);
              m_DiffRequestGraph.addNode(forwRequest, /*isSource=*/true);
            }
          }
```

File: lib/Differentiator/BaseForwardModeVisitor.cpp [hunk 6]
```diff
@@ -1117,9 +1119,95 @@ StmtDiff BaseForwardModeVisitor::VisitCallExpr(const CallExpr* CE) {
...
+        if (const auto* DRE = dyn_cast<DeclRefExpr>(cleanArg)) {
+          if (const auto* VD = dyn_cast<VarDecl>(DRE->getDecl())) {
+
+            std::size_t arrSize = 0;
+
+            // Try to get the size from the AST.
+            if (const auto* CAT =
+                    m_Context.getAsConstantArrayType(VD->getType())) {
+              arrSize = CAT->getSize().getZExtValue();
+            }
```
Comment (vgvassilev) [inline lib/Differentiator/BaseForwardModeVisitor.cpp:1146]: Can we test this code path?

File: lib/Differentiator/BaseForwardModeVisitor.cpp [hunk 7]
```diff
@@ -1117,9 +1119,106 @@ StmtDiff BaseForwardModeVisitor::VisitCallExpr(const CallExpr* CE) {
...
+
+            // If array size was found construct AST node for arg[k] for all k.
+            if (arrSize > 0) {
+              QualType elemType =
+                  QualType(arg->getType()->getPointeeOrArrayElementType(), 0);
+
+              llvm::APInt sizeAPI(
+                  m_Context.getTypeSize(m_Context.getSizeType()), arrSize);
+#if CLANG_VERSION_MAJOR >= 18
```
Comment (vgvassilev) [inline lib/Differentiator/BaseForwardModeVisitor.cpp]: When we use `clad_compat::getConstantArrayType` we don't need ifdefs.

File: lib/Differentiator/BaseForwardModeVisitor.cpp (hunk 6 above)
Comment (Fermats-Last-Theorem) [reply lib/Differentiator/BaseForwardModeVisitor.cpp:1146]: Added

File: lib/Differentiator/BaseForwardModeVisitor.cpp (hunk 7 above)
Comment (Fermats-Last-Theorem) [reply lib/Differentiator/BaseForwardModeVisitor.cpp]: Sorry I missed that, fixed.
