### PR TITLE
Reduce tape usage for objects

### LINKED ISSUE #1276: Incorrect derivative result because class type variable are not restored
Clad emits incorrect derivative result because class type variable are not restored.

Reproducible example:

```cpp
#define show(x) std::cout << #x << ": " << x << "\n";

class A {
public:
  void increment() { data++; }
  void setData(double u) { data = u; }
  double data = 0;
};

double fn(double u, double v) {
  double res = 0;
  A a;
  a.setData(u);
  res += a.data * v;
  a.increment();
  return res;
}

int main() {
  auto d_fn = clad::gradient(fn);
  double du = 0, dv = 0;
  d_fn.execute(3, 5, &du, &dv);
  show(du);
  show(dv);
}
```

**Output:**
```
du: 5
dv: 4
```

**Expected:**
```
du: 5
dv: 3
```

### PR DESCRIPTION
**Pull request by PetroZarytskyi**
We switched from the `store per use` to `store per change` system in reverse mode a while ago, i.e.
instead of
```
_t0 = x;
f(x);  // x passed by reference
...
f_pullback(_t0); // we use a different _t variable for every use
```
we do
```
_t0 = x;
f(x); // x passed by reference
...
x = _t0; // this way, we can reuse x many times per one change
f_pullback(x);
```
However, we haven't completed it for objects. Other parts of Clad expect original objects to be set to correct values, this inconsistency sometimes results in bugs like #1276. This PR implements the `store per change` system for method call bases.
Another big advantage of this approach is decreased tape usage, as we don't have to store bases of const methods of ones represented with temporary expressions. Also, in the future, we can extend TBR analysis and make it go into called functions so that we can remove even more stores.

Fixes #1276.

### CODE REVIEW

File: include/clad/Differentiator/STLBuiltins.h [hunk 1]
```diff
@@ -409,14 +409,14 @@ void push_back_reverse_forw(::std::vector<T>* v, U val, ::std::vector<T>* d_v,
 }
 
 template <typename T, typename U, typename pU>
-void push_back_pullback(::std::vector<T>* v, U val, ::std::vector<T>* d_v,
+void push_back_pullback(const ::std::vector<T>* v, U val, ::std::vector<T>* d_v,
```
Comment (vgvassilev) [inline include/clad/Differentiator/STLBuiltins.h:412]: Can we split this into a separate PR with also diagnostic?

Comment (PetroZarytskyi) [reply include/clad/Differentiator/STLBuiltins.h]: Fixed.
