### PR TITLE
Fix seg fault for catch(...)

### LINKED ISSUE #86: Cloning try-block with catch(...) causes SegFault in StmtClone::CloneDecl
Can be reproduced with:

```
int f(int x) 
  try { return x; }
  catch(...) { return 0; }
...
clad::differentiate(f, 0);
```

### PR DESCRIPTION
**Pull request by vaithak**
fixes #86

### CODE REVIEW

File: lib/Differentiator/StmtClone.cpp [hunk 1]
```diff
@@ -426,7 +426,10 @@ DEFINE_CLONE_STMT(ForStmt, (Ctx, Clone(Node->getInit()), Clone(Node->getCond()),
                             Node->getForLoc(), Node->getLParenLoc(), Node->getRParenLoc()))
 DEFINE_CLONE_STMT(ContinueStmt, (Node->getContinueLoc()))
 DEFINE_CLONE_STMT(BreakStmt, (Node->getBreakLoc()))
-DEFINE_CLONE_STMT(CXXCatchStmt, (Node->getCatchLoc(), static_cast<VarDecl*>(CloneDecl(Node->getExceptionDecl())), Clone(Node->getHandlerBlock())))
+DEFINE_CLONE_STMT(CXXCatchStmt, (Node->getCatchLoc(),
+                                 static_cast<VarDecl*>(
+                                     CloneDeclOrNull(Node->getExceptionDecl())),
+                                 Clone(Node->getHandlerBlock())))
```
Comment (vgvassilev) [inline lib/Differentiator/StmtClone.cpp:432]:
```suggestion
DEFINE_CLONE_STMT(CXXCatchStmt, (Node->getCatchLoc(),                                      CloneDeclOrNull(Node->getExceptionDecl()), Clone(Node->getHandlerBlock())))
```

Comment (vaithak) [reply lib/Differentiator/StmtClone.cpp]: removed the `statiic_cast` and ran clang-format again 👍🏼

Comment (vgvassilev) [reply lib/Differentiator/StmtClone.cpp]: Either way the formatting looks ugly... let's move forward.
